export type ApiError = {
  error: string;
  action?: string;
  kind?: string;
  // Present on /api/static-ads/recreate failures so the UI can render a
  // specific explanation and decide whether retry is worth offering.
  errorCode?: string;
  retryable?: boolean;
  rawError?: string;
};

/**
 * Error thrown by post() on non-OK responses. Carries the structured fields
 * from the server payload so callers can branch on them without re-parsing.
 */
export class ApiCallError extends Error {
  errorCode?: string;
  retryable?: boolean;
  rawError?: string;
  status: number;
  constructor(status: number, payload: ApiError) {
    super(payload.error || `Request failed: ${status}`);
    this.name = "ApiCallError";
    this.status = status;
    this.errorCode = payload.errorCode;
    this.retryable = payload.retryable;
    this.rawError = payload.rawError;
  }
}

export type TextGenResponse = {
  id: string | null;
  action: string;
  promptVersion: string;
  model: string;
  text: string;
  tokensIn: number;
  tokensOut: number;
  costUsd: number;
  durationMs: number;
};

export type MediaGenResponse = {
  id: string | null;
  action: string;
  model: string;
  urls: string[];
  durationMs: number;
};

async function post<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(path, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
  });
  const payload = (await res.json().catch(() => ({}))) as T | ApiError;
  if (!res.ok) {
    throw new ApiCallError(res.status, payload as ApiError);
  }
  return payload as T;
}

export function generateText(
  action: string,
  vars: Record<string, unknown> = {},
  opts: { model?: string; maxTokens?: number; meta?: { pipelineCardId?: string } } = {},
): Promise<TextGenResponse> {
  return post<TextGenResponse>(`/api/generate/text/${action}`, { vars, ...opts });
}

export function generateImage(
  action: string,
  args: { vars?: Record<string, unknown>; model?: string; input?: Record<string, unknown> } = {},
): Promise<MediaGenResponse> {
  return post<MediaGenResponse>(`/api/generate/image/${action}`, args);
}

export function generateVideo(
  action: string,
  args: { vars?: Record<string, unknown>; model?: string; input?: Record<string, unknown> } = {},
): Promise<MediaGenResponse> {
  return post<MediaGenResponse>(`/api/generate/video/${action}`, args);
}

// ---------- Brands ----------

/**
 * @deprecated The brand identity is now stored as a raw markdown style
 * guide on `Brand.guidelinesMarkdown` (generated by the Brand Guidelines
 * Generator skill — see prompts/brand_guidelines.md). This JSON shape is
 * still present on legacy brand rows that haven't been re-extracted
 * yet; existing code paths that read it should migrate to reading the
 * markdown instead.
 */
export type BrandResearch = {
  name?: string;
  websiteUrl?: string;
  logoUrl?: string | null;
  description?: string;
  tone?: string;
  colorPalette?: Array<{ name: string; hex: string; usage: string }>;
  fonts?: Array<{ name: string; usage: string; weight: string }>;
  [key: string]: unknown;
};

/**
 * One uploaded real typeface for a brand. `family` MUST match the font name in
 * the guidelines Typography section so the CSS `font-family` a generation emits
 * resolves to the `@font-face` the renderer injects from these files.
 */
export type BrandFontFace = {
  role: "heading" | "body" | "accent";
  family: string;
  regularUrl: string | null;
  italicUrl?: string | null;
  fallback: "serif" | "sans-serif" | "cursive" | "monospace";
};

export type Brand = {
  id: string;
  createdAt: string;
  name: string;
  brandUrl: string | null;
  logoUrl: string | null;
  /**
   * The 8-section brand guidelines markdown — single source of truth.
   * Rendered beautifully in BrandInfoPage and injected into every
   * downstream creative tool's prompt. Empty / null until the
   * brand_guidelines extraction completes (`researchStatus !== "complete"`).
   */
  guidelinesMarkdown: string | null;
  /** @deprecated — legacy JSON dossier kept until boot-time backfill regenerates as markdown. */
  research: BrandResearch | null;
  /**
   * Real, client-supplied font FILES (hosted on fal.storage) — one entry per
   * role, keyed to the family named in the guidelines Typography section. When
   * present, the listicle renderer embeds these via `@font-face` so landers
   * render in the genuine typeface. null / [] = fall back to the named web font.
   */
  brandFonts: BrandFontFace[] | null;
  researchStatus: "pending" | "researching" | "complete" | "failed";
  researchError: string | null;
  /**
   * Marks this brand as a Done-For-You client. Only DFY-flagged brands expose
   * the Client Console (share links + feedback inbox) in the nav.
   * Toggled by an admin in Settings → Clients. Defaults to false.
   */
  isDfyClient?: boolean;
};

async function get<T>(path: string): Promise<T> {
  const res = await fetch(path);
  const payload = (await res.json().catch(() => ({}))) as T | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as T;
}

async function del<T>(path: string, body?: unknown): Promise<T> {
  const res = await fetch(path, {
    method: "DELETE",
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const payload = (await res.json().catch(() => ({}))) as T | ApiError;
  if (!res.ok) {
    throw new ApiCallError(res.status, payload as ApiError);
  }
  return payload as T;
}

async function put<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(path, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
  });
  const payload = (await res.json().catch(() => ({}))) as T | ApiError;
  if (!res.ok) {
    throw new ApiCallError(res.status, payload as ApiError);
  }
  return payload as T;
}

async function patch<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(path, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
  });
  const payload = (await res.json().catch(() => ({}))) as T | ApiError;
  if (!res.ok) {
    throw new ApiCallError(res.status, payload as ApiError);
  }
  return payload as T;
}

export function listBrands(): Promise<{ brands: Brand[] }> {
  return get<{ brands: Brand[] }>("/api/brands");
}

export function getBrand(id: string): Promise<{ brand: Brand }> {
  return get<{ brand: Brand }>(`/api/brands/${id}`);
}

export function createBrand(args: {
  brandUrl: string;
  productUrl?: string;
  factSheet?: string;
  productName?: string;
  productImageUrl: string;
  // Back image is optional — front shot alone is enough for every
  // downstream generator. Server stores NULL when omitted.
  productBackImageUrl?: string;
}): Promise<{ brand: Brand; product: Product }> {
  return post<{ brand: Brand; product: Product }>("/api/brands", args);
}

export async function patchBrand(
  id: string,
  patch: {
    name?: string;
    brandUrl?: string | null;
    logoUrl?: string | null;
    /** Save edits to the markdown style guide. Writes overwrite brand.guidelinesMarkdown. */
    guidelinesMarkdown?: string;
    /** @deprecated — legacy JSON shape; new code writes guidelinesMarkdown. */
    research?: BrandResearch;
    /** Real uploaded font files; server sanitises before storing on brand.brandFonts. */
    brandFonts?: BrandFontFace[];
  },
): Promise<{ brand: Brand }> {
  const res = await fetch(`/api/brands/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
  const payload = (await res.json().catch(() => ({}))) as { brand: Brand } | ApiError;
  if (!res.ok) throw new Error((payload as ApiError)?.error ?? `Request failed: ${res.status}`);
  return payload as { brand: Brand };
}

export function retriggerBrandResearch(id: string): Promise<{ ok: true }> {
  return post<{ ok: true }>(`/api/brands/${id}/research`, {});
}

/**
 * Toggle a brand's Done-For-You client flag. Admin-only on the server
 * (`PATCH /api/brands/:id/dfy`). Flipping this on exposes the Client Command
 * Center for the brand; flipping it off hides it again.
 */
export async function setBrandDfyClient(
  id: string,
  isDfyClient: boolean,
): Promise<{ brand: Brand }> {
  const res = await fetch(`/api/brands/${id}/dfy`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ isDfyClient }),
  });
  const payload = (await res.json().catch(() => ({}))) as { brand: Brand } | ApiError;
  if (!res.ok) throw new ApiCallError(res.status, payload as ApiError);
  return payload as { brand: Brand };
}

export function uploadProductImageRaw(
  dataUrl: string,
  filename?: string,
): Promise<{ url: string }> {
  return post<{ url: string }>("/api/uploads/product-image", { dataUrl, filename });
}

/**
 * Upload a brand logo. The server rasterises SVG inputs to PNG before
 * storing, so the returned URL is always safe for downstream b-roll /
 * message-testing pipelines (which reject SVG references). `converted`
 * tells the caller whether a conversion happened, useful for UX copy
 * ("Logo converted from SVG to PNG").
 */
export function uploadBrandLogoRaw(
  dataUrl: string,
  filename?: string,
): Promise<{ url: string; converted: boolean }> {
  return post<{ url: string; converted: boolean }>("/api/uploads/brand-logo", { dataUrl, filename });
}

/**
 * Upload a real brand font file (.woff2 / .woff / .otf / .ttf). Hosts it on
 * fal.storage and returns the URL to record on the brand's `brandFonts`. The
 * server preserves the extension so the renderer can pick the right
 * `@font-face` format hint.
 */
export function uploadBrandFontRaw(
  dataUrl: string,
  filename?: string,
): Promise<{ url: string }> {
  return post<{ url: string }>("/api/uploads/brand-font", { dataUrl, filename });
}

// ---------- Products ----------

/**
 * The three lazily-generated sub-artifacts each angle owns, in addition to its
 * `block` (the elaborated description):
 *   - statements → authentic customer resonance statements (web-mined)
 *   - messages   → 10 first-person ad messages
 *   - adCopy     → a complete primary ad
 */
export type AngleArtifactKind = "statements" | "messages" | "adCopy";

export type AngleArtifact = {
  content?: string | null;
  status?: SubJobStatus; // running | complete | failed; absent = not generated
  error?: string | null;
  generatedAt?: string;
};

export type ProductAngle = {
  // `id` is backfilled lazily server-side; older cached angles may briefly
  // lack it until the next GET heals + persists it.
  id?: string;
  name: string;
  block: string;
  artifacts?: Partial<Record<AngleArtifactKind, AngleArtifact>>;
};

export type ProductImageCandidate = {
  url: string;
  width: number | null;
  height: number | null;
  source: string;
  score: number;
};

export type ProductMechanismEntry = {
  product_id: string;
  physical_description: string;
  container_material: string;
  opening: string;
  dispensing: string;
  closing: string;
  content_color: string;
  viscosity: string;
};

export type SubJobStatus = "running" | "complete" | "failed";

export type ProductResearchPayload = {
  markdown?: string;
  angles?: ProductAngle[];
  imageCandidates?: ProductImageCandidate[];
  mechanism?: ProductMechanismEntry[];
  mechanismStatus?: SubJobStatus;
  mechanismError?: string | null;
  mechanismGeneratedAt?: string;
  mechanismEditedAt?: string;
  referenceSheetUrl?: string;
  referenceSheetStatus?: SubJobStatus;
  referenceSheetError?: string | null;
  referenceSheetGeneratedAt?: string;
  model?: string;
  promptVersion?: string;
  tokensIn?: number;
  tokensOut?: number;
  costUsd?: number;
  durationMs?: number;
  completedAt?: string;
};

export type Product = {
  id: string;
  createdAt: string;
  brandId: string;
  name: string;
  category: string;
  productUrl: string | null;
  factSheet: string | null;
  productImageUrl: string | null;
  productBackImageUrl: string | null;
  contentImageUrl: string | null;
  research: ProductResearchPayload | null;
  researchStatus: "pending" | "researching" | "complete" | "failed";
  researchError: string | null;
  // Phase 2 client share link. NULL/absent = not shared. Present = the
  // read-only public doc is live at /share/<shareToken>.
  shareToken?: string | null;
};

export function listProducts(brandId: string): Promise<{ products: Product[] }> {
  return get<{ products: Product[] }>(`/api/products?brandId=${encodeURIComponent(brandId)}`);
}

export function getProduct(id: string): Promise<{ product: Product }> {
  return get<{ product: Product }>(`/api/products/${id}`);
}

export function createProduct(args: {
  brandId: string;
  productUrl?: string;
  factSheet?: string;
  name?: string;
  category?: string;
  productImageUrl?: string;
  productBackImageUrl?: string;
  contentImageUrl?: string;
}): Promise<{ product: Product }> {
  return post<{ product: Product }>("/api/products", args);
}

export function retriggerResearch(id: string): Promise<{ ok: true }> {
  return post<{ ok: true }>(`/api/products/${id}/research`, {});
}

/**
 * Operator MANUAL edit of the product research markdown (PUT). Overwrites
 * research.markdown verbatim and preserves the angles + other research fields.
 * Re-fetch getProduct() afterwards to render the new diagnosis.
 */
export function updateProductResearch(id: string, markdown: string): Promise<{ ok: true }> {
  return put<{ ok: true }>(`/api/products/${id}/research`, { markdown });
}

/**
 * Rename a product (or, in the future, update other simple fields).
 * Currently the PATCH endpoint only accepts `name`; the heavier fields
 * (mechanism, reference sheet, research, images) each have their own
 * dedicated routes because they trigger downstream regeneration.
 */
export async function patchProduct(
  id: string,
  updates: { name?: string },
): Promise<{ product: Product }> {
  const res = await fetch(`/api/products/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(updates),
  });
  const payload = (await res.json().catch(() => ({}))) as { product: Product } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { product: Product };
}

export async function deleteProduct(id: string): Promise<{ ok: true; id: string }> {
  const res = await fetch(`/api/products/${id}`, { method: "DELETE" });
  const payload = (await res.json().catch(() => ({}))) as { ok: true; id: string } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { ok: true; id: string };
}

export function getProductAngles(id: string): Promise<{ angles: ProductAngle[]; cached: boolean }> {
  return get<{ angles: ProductAngle[]; cached: boolean }>(`/api/products/${id}/angles`);
}

/**
 * Elaborates a user-supplied strategic angle description into a full angle
 * block and appends it to the product's research.angles array. The server
 * runs the angle_elaborate master prompt for this single angle only — the
 * existing angles and research markdown are left untouched.
 */
export function addProductAngle(
  productId: string,
  description: string,
): Promise<{ angle: ProductAngle; angles: ProductAngle[] }> {
  return post<{ angle: ProductAngle; angles: ProductAngle[] }>(
    `/api/products/${productId}/angles`,
    { description },
  );
}

/**
 * Append a pre-written angle VERBATIM (no AI) — the "paste an angle" mode.
 * Stores `name` + `block` as-is on research.angles. Any of the optional
 * artifacts (statements / messages / adCopy) provided are saved as the angle's
 * complete sub-artifacts in the same call, so a whole angle can be pasted in one
 * go. Use when the operator already has a finished/approved angle.
 */
export function addProductAngleManual(
  productId: string,
  name: string,
  block: string,
  artifacts?: { statements?: string; messages?: string; adCopy?: string },
): Promise<{ angle: ProductAngle; angles: ProductAngle[] }> {
  return post<{ angle: ProductAngle; angles: ProductAngle[] }>(
    `/api/products/${productId}/angles`,
    { name, block, ...(artifacts ?? {}) },
  );
}

/**
 * Kicks off lazy generation of one sub-artifact (statements / messages /
 * adCopy) for one angle. Returns immediately — the server flips the artifact's
 * status to "running" and generates async; poll getProduct() to watch it
 * become "complete"/"failed" and read the cached content off
 * research.angles[i].artifacts[kind].
 */
export function generateAngleArtifact(
  productId: string,
  angleId: string,
  kind: AngleArtifactKind,
): Promise<{ ok: true }> {
  return post<{ ok: true }>(
    `/api/products/${productId}/angles/${encodeURIComponent(angleId)}/artifact`,
    { kind },
  );
}

/**
 * Operator MANUAL edit of one angle's message/adCopy copy. Overwrites the live
 * cached artifact with hand-typed text (marked "complete"). Only "messages" and
 * "adCopy" are hand-editable — "statements" is web-mined and must be
 * regenerated. Re-fetch getProduct() afterwards to pick up the new content.
 */
export function updateAngleArtifactContent(
  productId: string,
  angleId: string,
  kind: "messages" | "adCopy",
  content: string,
): Promise<{ ok: true }> {
  return put<{ ok: true }>(
    `/api/products/${productId}/angles/${encodeURIComponent(angleId)}/artifact`,
    { kind, content },
  );
}

/**
 * Operator MANUAL edit of one angle's DESCRIPTION (the elaborated `block`
 * markdown). Overwrites research.angles[i].block with hand-typed text, verbatim;
 * the angle's cached sub-artifacts (statements / messages / adCopy) and every
 * sibling angle are left untouched. `block` is stored raw — the read view still
 * hides any "Customer Statements" subsection on display. Returns the updated
 * angles list so the caller can re-render without a refetch.
 */
export function updateProductAngle(
  productId: string,
  angleId: string,
  block: string,
): Promise<{ angles: ProductAngle[] }> {
  return patch<{ angles: ProductAngle[] }>(
    `/api/products/${productId}/angles/${encodeURIComponent(angleId)}`,
    { block },
  );
}

/**
 * Permanently delete one strategic angle (and all its cached artifacts) from a
 * product's research. Returns the remaining angles so the caller can re-render
 * without a refetch. Irreversible — the operator UI gates this behind a
 * type-DELETE confirmation.
 */
export function deleteProductAngle(
  productId: string,
  angleId: string,
): Promise<{ angles: ProductAngle[] }> {
  return del<{ angles: ProductAngle[] }>(
    `/api/products/${productId}/angles/${encodeURIComponent(angleId)}`,
  );
}

/**
 * Extract the front-end offer from the product's page URL (productUrl).
 * Fetches the page, runs the `offer_extract` prompt, and returns:
 *   - `offer`: a concise plain-English summary suitable for the Copy Engine's
 *     "front-end offer" field (null if nothing was extractable or the page
 *     was unreachable).
 *   - `structured`: the full JSON object returned by the offer_extract prompt
 *     (discount_label, free_gifts, shipping_line, guarantee_line, …), or null
 *     on total failure.
 *
 * Never throws on bad pages — the server returns 200 with null fields when
 * the product URL is unfetchable or the LLM can't find an offer.
 */
export function extractProductOffer(
  productId: string,
): Promise<{ offer: string | null; structured: unknown }> {
  return post<{ offer: string | null; structured: unknown }>(
    `/api/products/${productId}/extract-offer`,
    {},
  );
}

// ── Phase 2: read-only client share link ──────────────────────────────
// Operator-side (authed): mint/rotate and revoke the share token.
// Public-side: getSharedResearch reads the sanitized doc by token (no auth).

/**
 * Mint (or rotate) the product's client share token. Returns the fresh token;
 * the shareable URL is `${location.origin}/share/${shareToken}`. Calling again
 * rotates the token, instantly invalidating any previously-shared URL.
 */
export function createShareLink(productId: string): Promise<{ shareToken: string }> {
  return post<{ shareToken: string }>(`/api/products/${productId}/share`, {});
}

/** Revoke the product's share link (the public URL 404s immediately after). */
export function revokeShareLink(productId: string): Promise<{ ok: true }> {
  return del<{ ok: true }>(`/api/products/${productId}/share`);
}

/** A sub-artifact (statements / messages / adCopy) as seen by the client doc. */
export type SharedArtifact = {
  content: string | null;
  status: SubJobStatus | null;
};

export type SharedAngle = {
  id: string;
  name: string;
  block: string;
  artifacts: Partial<Record<AngleArtifactKind, SharedArtifact>>;
};

/** Sanitized, public, read-only research payload returned by GET /api/share/:token. */
export type SharedResearchPayload = {
  brand: { name: string; logoUrl: string | null };
  product: { name: string };
  research: {
    markdown: string | null;
    angles: SharedAngle[];
  };
};

/**
 * Public fetch of the shared research document by token. NO auth/cookies
 * required. Throws (404) when the token is missing, revoked, or unknown — the
 * ClientSharePage maps that to an "invalid or expired link" state.
 */
export function getSharedResearch(token: string): Promise<SharedResearchPayload> {
  return get<SharedResearchPayload>(`/api/share/${encodeURIComponent(token)}`);
}

// ── Phase 3: client feedback ───────────────────────────────────────────
// One-way Approve/Needs-changes + optional note, keyed by the same section
// anchors the checklist uses. Public fns write through the token-gated share
// router; operator fns read + triage through the authed products router.

export type FeedbackVerdict = "approved" | "changes";
export type FeedbackSectionKind = "angle" | "messages" | "adCopy";
export type FeedbackStatus = "open" | "resolved";

/** The client's own feedback for one section, as returned by the public route. */
export type ShareFeedback = {
  anchorId: string;
  sectionKind: FeedbackSectionKind;
  verdict: FeedbackVerdict;
  note: string | null;
  clientName: string | null;
  suggestion: string | null;
  suggestionStatus: FeedbackSuggestionStatus;
  suggestionError: string | null;
  updatedAt: string;
};

/** Public: the client's submitted feedback for this share link (rehydrates the checklist). */
export function getShareFeedback(token: string): Promise<{ feedback: ShareFeedback[] }> {
  return get<{ feedback: ShareFeedback[] }>(`/api/share/${encodeURIComponent(token)}/feedback`);
}

/** Public: upsert the client's verdict + optional note for one section. */
export function submitShareFeedback(
  token: string,
  anchorId: string,
  body: { verdict: FeedbackVerdict; note?: string; clientName?: string },
): Promise<{ feedback: ShareFeedback }> {
  return put<{ feedback: ShareFeedback }>(
    `/api/share/${encodeURIComponent(token)}/feedback/${encodeURIComponent(anchorId)}`,
    body,
  );
}

/** Public: clear the client's feedback for one section (undo). */
export function clearShareFeedback(token: string, anchorId: string): Promise<{ ok: true }> {
  return del<{ ok: true }>(
    `/api/share/${encodeURIComponent(token)}/feedback/${encodeURIComponent(anchorId)}`,
  );
}

/**
 * Public: the CLIENT accepts the AI revision generated for one section. This
 * applies the revision to the LIVE copy IMMEDIATELY (status → "applied") — there
 * is no operator approval step. The feedback stays open so the operator gets a
 * notification to acknowledge. Re-fetch getSharedResearch() after this resolves
 * so the displayed copy reflects the applied change. Only valid while "ready".
 */
export function acceptShareSuggestion(
  token: string,
  anchorId: string,
): Promise<{ feedback: ShareFeedback }> {
  return post<{ feedback: ShareFeedback }>(
    `/api/share/${encodeURIComponent(token)}/feedback/${encodeURIComponent(anchorId)}/suggestion/accept`,
    {},
  );
}

/**
 * Public: the CLIENT declines the AI revision and asks the team to handle their
 * note manually ("Send for manual review"). Keeps the original copy and leaves
 * the feedback open. Only valid while status is "ready".
 */
export function declineShareSuggestion(
  token: string,
  anchorId: string,
): Promise<{ feedback: ShareFeedback }> {
  return post<{ feedback: ShareFeedback }>(
    `/api/share/${encodeURIComponent(token)}/feedback/${encodeURIComponent(anchorId)}/suggestion/decline`,
    {},
  );
}

/**
 * State of the client-driven AI revision proposal stashed on a feedback item:
 *   null        — no proposal (approval, angle-level note, or nothing to revise)
 *   "ready"     — generated and waiting on the CLIENT to accept or decline
 *   "applied"   — client accepted; the revision was written LIVE immediately.
 *                 Feedback stays open so the operator can acknowledge it.
 *   "declined"  — client kept the original ("Send for manual review")
 *   "failed"    — generation errored; see `suggestionError`
 */
export type FeedbackSuggestionStatus =
  | "ready"
  | "applied"
  | "declined"
  | "failed"
  | null;

/** Operator-side feedback row — the full triage view (includes status + ids). */
export type OperatorFeedback = {
  id: string;
  anchorId: string;
  angleId: string;
  angleName: string | null;
  sectionKind: FeedbackSectionKind;
  verdict: FeedbackVerdict;
  note: string | null;
  clientName: string | null;
  status: FeedbackStatus;
  suggestion: string | null;
  suggestionStatus: FeedbackSuggestionStatus;
  suggestionError: string | null;
  /** The live copy at the moment the (now applied) revision was generated. */
  suggestionOriginal: string | null;
  createdAt: string;
  updatedAt: string;
};

/** Operator: all client feedback collected for a product (inbox + inline). */
export function getProductFeedback(productId: string): Promise<{ feedback: OperatorFeedback[] }> {
  return get<{ feedback: OperatorFeedback[] }>(`/api/products/${productId}/feedback`);
}

/** Operator: triage a single feedback item (open ↔ resolved). */
export async function updateFeedbackStatus(
  productId: string,
  feedbackId: string,
  status: FeedbackStatus,
): Promise<{ feedback: OperatorFeedback }> {
  const res = await fetch(`/api/products/${productId}/feedback/${feedbackId}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ status }),
  });
  const payload = (await res.json().catch(() => ({}))) as { feedback: OperatorFeedback } | ApiError;
  if (!res.ok) throw new ApiCallError(res.status, payload as ApiError);
  return payload as { feedback: OperatorFeedback };
}

// NOTE: There are no operator apply/dismiss functions. In the client-driven
// flow the client both generates AND applies the AI revision live (see
// acceptShareSuggestion). The operator only observes the applied before→after
// (suggestionOriginal → suggestion) and acknowledges it with updateFeedbackStatus
// ("mark as read" = open → resolved).

export function uploadProductImage(
  id: string,
  dataUrl: string,
  filename?: string,
): Promise<{ url: string; candidate: ProductImageCandidate; imageCandidates: ProductImageCandidate[] }> {
  return post(`/api/products/${id}/upload-image`, { dataUrl, filename });
}

export function setProductMainImage(id: string, url: string): Promise<{ ok: true; productImageUrl: string }> {
  return post(`/api/products/${id}/main-image`, { url });
}

export function addProductImageCandidate(
  id: string,
  url: string,
): Promise<{ ok: true; candidate?: ProductImageCandidate; imageCandidates: ProductImageCandidate[] }> {
  return post(`/api/products/${id}/image-candidate`, { url });
}

export function deleteProductImageCandidate(
  id: string,
  url: string,
): Promise<{ ok: true; imageCandidates: ProductImageCandidate[]; productImageUrl: string | null }> {
  return del(`/api/products/${id}/image-candidate`, { url });
}

export type ReferenceStyleResponse =
  | { missing: true; message: string }
  | {
      missing?: undefined;
      referenceImageUrl: string;
      style: Record<string, unknown>;
      cached: boolean;
      extractedAt: string;
    };

export async function getReferenceStyle(): Promise<ReferenceStyleResponse> {
  const res = await fetch("/api/message-testing/reference-style");
  const payload = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(payload?.error ?? `Request failed: ${res.status}`);
  return payload as ReferenceStyleResponse;
}

export type ProductMechanism = {
  product_id: string;
  physical_description: string;
  container_material: string;
  opening: string;
  dispensing: string;
  closing: string;
  content_color: string;
  viscosity: string;
};

export function getProductMechanism(id: string): Promise<{ mechanism: ProductMechanism[]; cached: boolean }> {
  return get<{ mechanism: ProductMechanism[]; cached: boolean }>(`/api/products/${id}/mechanism`);
}

export function generateReferenceSheet(
  id: string,
  opts: { feedback?: string } = {},
): Promise<{ ok: true }> {
  // When feedback is provided, the server uses the existing reference sheet
  // as the edit base (nano-banana-pro/edit) and applies the feedback as a
  // targeted change rather than regenerating from scratch.
  const body: { feedback?: string } = {};
  if (opts.feedback && opts.feedback.trim()) body.feedback = opts.feedback.trim();
  return post<{ ok: true }>(`/api/products/${id}/reference-sheet`, body);
}

/**
 * Save a user-edited mechanism array. The server validates the shape and
 * writes it to research.mechanism — mechanismStatus stays "complete" and
 * the downstream B-roll / image pipelines will read the edited values on
 * the next run.
 */
export async function updateProductMechanism(
  id: string,
  mechanism: ProductMechanism[],
): Promise<{ ok: true; mechanism: ProductMechanism[] }> {
  const res = await fetch(`/api/products/${id}/mechanism`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ mechanism }),
  });
  const payload = (await res.json().catch(() => ({}))) as
    | { ok: true; mechanism: ProductMechanism[] }
    | ApiError;
  if (!res.ok) throw new ApiCallError(res.status, payload as ApiError);
  return payload as { ok: true; mechanism: ProductMechanism[] };
}

// ---------- B-Roll ----------

export type BrollShot = {
  id: number;
  shot_type: "Unboxing" | "Product Presentation" | "Product Usage" | "Proof / Results";
  action: string;
  location: string;
  visual_example: string;
  // Optional: the LATEST rendered image prompt for this shot, including any
  // feedback the user appended during image regen. Passed into the video
  // prompt writer so the motion description matches the actual still — not
  // the original generic shot metadata. Without this, image feedback like
  // "make the lighting warmer" was lost when the video prompt was written.
  image_prompt?: string;
};

export type BrollShotList = {
  project: string;
  location_default: string;
  shots: BrollShot[];
};

export async function generateBrollShots(args: {
  product: string;
  research: string;
  assetLimits?: string;
}): Promise<{ shots: BrollShotList; meta: TextGenResponse }> {
  const meta = await generateText("broll_shots_generate", {
    product: args.product,
    research: args.research,
    assetLimits: args.assetLimits ?? "",
  });
  let parsed: BrollShotList;
  try {
    parsed = JSON.parse(meta.text);
  } catch {
    const m = meta.text.match(/\{[\s\S]*\}/);
    if (!m) throw new Error("Shot list generator did not return valid JSON");
    parsed = JSON.parse(m[0]);
  }
  return { shots: parsed, meta };
}

/**
 * Splits a paragraph-style response (image or video prompt writer) on lines
 * containing only `*`. Trims each paragraph. Filters empties.
 */
function splitStarredParagraphs(text: string): string[] {
  return text
    .split(/^\s*\*+\s*$/m)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);
}

export async function generateBrollImagePrompts(args: {
  product: string;
  mechanism: unknown;
  avatar?: string;
  shots: BrollShot[];
}): Promise<{ prompts: string[]; meta: TextGenResponse }> {
  const meta = await generateText("broll_image_prompts", {
    product: args.product,
    avatar: args.avatar ?? "",
    mechanism: JSON.stringify(args.mechanism ?? [], null, 2),
    shots: JSON.stringify(args.shots, null, 2),
  });
  const prompts = splitStarredParagraphs(meta.text);
  if (prompts.length === 0) throw new Error("Image prompt writer returned no paragraphs");
  return { prompts, meta };
}

export async function generateBrollVideoPrompts(args: {
  product: string;
  mechanism: unknown;
  avatar?: string;
  shots: BrollShot[];
}): Promise<{ prompts: string[]; meta: TextGenResponse }> {
  const meta = await generateText("broll_video_prompts", {
    product: args.product,
    avatar: args.avatar ?? "",
    mechanism: JSON.stringify(args.mechanism ?? [], null, 2),
    shots: JSON.stringify(args.shots, null, 2),
  });
  const prompts = splitStarredParagraphs(meta.text);
  if (prompts.length === 0) throw new Error("Video prompt writer returned no paragraphs");
  return { prompts, meta };
}

// ---------- Character B-Roll ----------

export type CharacterBrollCategory =
  | "Hook / Scroll-Stopper"
  | "Problem"
  | "Failed Solution"
  | "Product"
  | "Authority / Credibility"
  | "Emotional Payoff / Transformation"
  | "Lifestyle / Context";

export type CharacterBrollShot = {
  id: number;
  category: CharacterBrollCategory | string;
  shot_type: string;
  action: string;
  location: string;
  visual_example: string;
  script_beat?: string;
  // Optional: the LATEST rendered image prompt for this shot, including any
  // feedback the user appended during image regen. Passed into the video
  // prompt writer so motion description matches the actual still.
  image_prompt?: string;
};

export type CharacterBrollShotList = {
  project: string;
  input_mode: "angle" | "script";
  character_ref: string;
  location_default: string;
  shots: CharacterBrollShot[];
};

export async function uploadCharacterImage(
  dataUrl: string,
  filename?: string,
): Promise<{ url: string }> {
  return post<{ url: string }>("/api/uploads/character-image", { dataUrl, filename });
}

/**
 * Character library — reference photos shown in the Character B-roll picker.
 * Two tiers, returned in one response: `defaults` are shared across every
 * brand (curated via the `client/public/characters/library/` seed folder),
 * `brand` are private to the active brand and uploaded via the UI.
 */
export type CharacterPrepStatus = "pending" | "running" | "complete" | "failed";

export type CharacterRef = {
  id: string;
  createdAt: string;
  brandId: string | null;
  title: string;
  /** Original image — used for image generation (Nano-Banana accepts realistic photos). */
  imageUrl: string;
  thumbnailUrl: string | null;
  sourcePath: string | null;
  sourceSignature: string | null;
  /**
   * Step 1 output — turnaround / reference sheet on white background.
   * Persisted for inspection / regen; not currently sent to any model directly.
   */
  seedanceSheetUrl: string | null;
  /**
   * Step 2 output — close-up synthetic portrait. THIS is what we pass to
   * Seedance ref-to-video as `@Image2`, never the original photo (the
   * likeness detector flags realistic photos as "real people").
   */
  seedancePortraitUrl: string | null;
  seedancePrepStatus: CharacterPrepStatus;
  seedancePrepError: string | null;
};

export function listCharacters(brandId: string | null): Promise<{ defaults: CharacterRef[]; brand: CharacterRef[] }> {
  const qs = brandId ? `?brandId=${encodeURIComponent(brandId)}` : "";
  return get<{ defaults: CharacterRef[]; brand: CharacterRef[] }>(`/api/characters${qs}`);
}

export function createCharacter(args: {
  brandId: string;
  dataUrl: string;
  filename?: string;
  title?: string;
}): Promise<{ character: CharacterRef }> {
  return post<{ character: CharacterRef }>("/api/characters", args);
}

export function prepareCharacterForSeedance(id: string): Promise<{ ok: true; queued: true }> {
  return post<{ ok: true; queued: true }>(`/api/characters/${id}/prepare-seedance`, {});
}

// ---------- Team & invites ----------

export type TeamRole = "admin" | "manager" | "member";

export type TeamMemberRow = {
  userId: string;
  name: string;
  email: string;
  role: TeamRole;
  joinedAt: string;
};

export type InviteRow = {
  id: string;
  email: string;
  role: TeamRole;
  token: string;
  invitedByUserId: string;
  expiresAt: string;
  acceptedAt: string | null;
  createdAt: string;
};

export type TeamSnapshot = {
  team: { id: string; name: string };
  role: TeamRole;
  members: TeamMemberRow[];
  invites: InviteRow[];
  acceptedInvites: InviteRow[];
};

export function getTeam(): Promise<TeamSnapshot> {
  return get<TeamSnapshot>("/api/team");
}

export function createTeamInvite(args: { email: string; role: TeamRole }): Promise<{ invite: InviteRow }> {
  return post<{ invite: InviteRow }>("/api/team/invites", args);
}

export async function revokeTeamInvite(id: string): Promise<{ ok: true }> {
  const res = await fetch(`/api/team/invites/${id}`, { method: "DELETE" });
  const payload = (await res.json().catch(() => ({}))) as { ok: true } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { ok: true };
}

export async function updateTeamMemberRole(userId: string, role: TeamRole): Promise<{ ok: true }> {
  const res = await fetch(`/api/team/members/${userId}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ role }),
  });
  const payload = (await res.json().catch(() => ({}))) as { ok: true } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { ok: true };
}

export async function removeTeamMember(userId: string): Promise<{ ok: true }> {
  const res = await fetch(`/api/team/members/${userId}`, { method: "DELETE" });
  const payload = (await res.json().catch(() => ({}))) as { ok: true } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { ok: true };
}

// ── Per-user × per-workspace access (admin-only) ──────────────────

export type MemberBrandAccess = {
  id: string;
  name: string;
  logoUrl: string | null;
  hasAccess: boolean;
};

export type MemberBrandAccessResponse = {
  isAdmin: boolean;
  brands: MemberBrandAccess[];
};

export async function getMemberBrands(userId: string): Promise<MemberBrandAccessResponse> {
  const res = await fetch(`/api/team/members/${userId}/brands`);
  const payload = (await res.json().catch(() => ({}))) as MemberBrandAccessResponse | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as MemberBrandAccessResponse;
}

export async function setMemberBrands(userId: string, brandIds: string[]): Promise<{ ok: true; granted?: number; revoked?: number }> {
  const res = await fetch(`/api/team/members/${userId}/brands`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ brandIds }),
  });
  const payload = (await res.json().catch(() => ({}))) as { ok: true; granted?: number; revoked?: number } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { ok: true; granted?: number; revoked?: number };
}

export type InvitePreview = { email: string; role: TeamRole; teamName: string | null };

export function previewInvite(token: string): Promise<InvitePreview> {
  return get<InvitePreview>(`/api/auth/invite/${token}`);
}

// ── Password reset (admin-issued link) ──

/** Admin: issue a one-time password-reset link for a team member. Returns the token to build the link. */
export function createPasswordReset(userId: string): Promise<{ token: string; expiresAt: string }> {
  return post<{ token: string; expiresAt: string }>(`/api/team/members/${userId}/reset-password`, {});
}

/** Public: validate a reset token, returning the target email to confirm on the page. */
export function previewPasswordReset(token: string): Promise<{ email: string }> {
  return get<{ email: string }>(`/api/auth/reset/${token}`);
}

/** Public: set a new password via a reset token. */
export function submitPasswordReset(token: string, password: string): Promise<{ ok: true }> {
  return post<{ ok: true }>(`/api/auth/reset/${token}`, { password });
}

export async function deleteCharacter(id: string): Promise<{ ok: true }> {
  const res = await fetch(`/api/characters/${id}`, { method: "DELETE" });
  const payload = (await res.json().catch(() => ({}))) as { ok: true } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { ok: true };
}

export async function generateCharacterBrollShots(args: {
  product: string;
  inputMode: "angle" | "script";
  research?: string;
  script?: string;
  assetLimits?: string;
}): Promise<{ shots: CharacterBrollShotList; meta: TextGenResponse }> {
  const meta = await generateText("character_broll_shots_generate", {
    product: args.product,
    inputMode: args.inputMode,
    research: args.research ?? "",
    script: args.script ?? "",
    assetLimits: args.assetLimits ?? "",
  });
  let parsed: CharacterBrollShotList;
  try {
    parsed = JSON.parse(meta.text);
  } catch {
    const m = meta.text.match(/\{[\s\S]*\}/);
    if (!m) throw new Error("Character shot list generator did not return valid JSON");
    parsed = JSON.parse(m[0]);
  }
  return { shots: parsed, meta };
}

export async function generateCharacterBrollImagePrompts(args: {
  product: string;
  mechanism: unknown;
  shots: CharacterBrollShot[];
}): Promise<{ prompts: string[]; meta: TextGenResponse }> {
  const meta = await generateText("character_broll_image_prompts", {
    product: args.product,
    mechanism: JSON.stringify(args.mechanism ?? [], null, 2),
    shots: JSON.stringify(args.shots, null, 2),
  });
  const prompts = splitStarredParagraphs(meta.text);
  if (prompts.length === 0) throw new Error("Image prompt writer returned no paragraphs");
  return { prompts, meta };
}

export async function generateCharacterBrollVideoPrompts(args: {
  product: string;
  mechanism: unknown;
  shots: CharacterBrollShot[];
}): Promise<{ prompts: string[]; meta: TextGenResponse }> {
  const meta = await generateText("character_broll_video_prompts", {
    product: args.product,
    mechanism: JSON.stringify(args.mechanism ?? [], null, 2),
    shots: JSON.stringify(args.shots, null, 2),
  });
  const prompts = splitStarredParagraphs(meta.text);
  if (prompts.length === 0) throw new Error("Video prompt writer returned no paragraphs");
  return { prompts, meta };
}

/**
 * Single-Scene Generator — image prompt writer.
 *
 * Takes free-form scene lines (one per scene the user wants to generate) plus
 * optional product context, returns one Nano-Banana-Pro-ready prompt per
 * scene line. Mirrors the b-roll image prompt writer in shape (one Anthropic
 * call → array of `*`-separated paragraphs) but the master prompt
 * (`prompts/single_scene_image_prompt.md`) is purpose-built for free-form
 * single-shot inputs rather than the 7-category B-roll arc.
 */
export async function generateSingleSceneImagePrompts(args: {
  product: string;
  mechanism: unknown;
  scenes: string[];
}): Promise<{ prompts: string[]; meta: TextGenResponse }> {
  const meta = await generateText("single_scene_image_prompt", {
    product: args.product,
    mechanism: JSON.stringify(args.mechanism ?? [], null, 2),
    scenes: args.scenes.map((s, i) => `${i + 1}. ${s}`).join("\n"),
  });
  const prompts = splitStarredParagraphs(meta.text);
  if (prompts.length === 0) throw new Error("Single-scene image prompt writer returned no paragraphs");
  return { prompts, meta };
}

// ---------- Brand Assets ----------

export type BrandAssetKind = "image" | "video" | "document" | "landing_page";

export type BrandAsset = {
  id: string;
  createdAt: string;
  kind: BrandAssetKind;
  url: string;
  thumbnailUrl: string | null;
  title: string;
  sourceApp: string;
  productId: string | null;
  metadata: Record<string, unknown> | null;
  userId: string | null;
  // Display name (or email local-part) of the user who saved this asset.
  // Server resolves this via a join + fallback so the client can render
  // directly without an extra lookup. Null for legacy rows / anon saves.
  creatorName: string | null;
};

export type NewBrandAssetInput = {
  kind: BrandAssetKind;
  url: string;
  title: string;
  sourceApp: string;
  thumbnailUrl?: string | null;
  productId?: string | null;
  metadata?: Record<string, unknown> | null;
};

export function listBrandAssets(brandId: string): Promise<{ assets: BrandAsset[] }> {
  return get<{ assets: BrandAsset[] }>(`/api/brand-assets?brandId=${encodeURIComponent(brandId)}`);
}

export function saveBrandAssets(
  brandId: string,
  assets: NewBrandAssetInput[],
): Promise<{ assets: BrandAsset[] }> {
  return post<{ assets: BrandAsset[] }>("/api/brand-assets", { brandId, assets });
}

export async function deleteBrandAsset(id: string): Promise<{ ok: true }> {
  const res = await fetch(`/api/brand-assets/${id}`, { method: "DELETE" });
  const payload = (await res.json().catch(() => ({}))) as { ok: true } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { ok: true };
}

// ---------- Message Testing ----------

export type MessageAngleGroup = { name: string; messages: string[] };

/**
 * Parses the `Angle: <name>\nmessage\nmessage\n...` format from
 * prompts/message_testing_copy.md. Blank lines separate angles.
 */
function parseMessagesByAngle(text: string): MessageAngleGroup[] {
  const lines = text.split("\n").map((l) => l.trim());
  const result: MessageAngleGroup[] = [];
  let current: MessageAngleGroup | null = null;
  for (const line of lines) {
    if (!line) continue;
    const m = line.match(/^Angle:\s*(.+)$/i);
    if (m) {
      if (current && current.messages.length > 0) result.push(current);
      current = { name: m[1].trim(), messages: [] };
    } else if (current) {
      // Strip stray leading bullets/quotes if the model slipped up.
      const cleaned = line.replace(/^[-•*]\s*/, "").replace(/^["'"]|["'"]$/g, "").trim();
      if (cleaned) current.messages.push(cleaned);
    }
  }
  if (current && current.messages.length > 0) result.push(current);
  return result;
}

// ---------- Jobs (durable generation jobs) ----------

/**
 * Durable server-side generation jobs — batches survive tab closes and
 * deploys; the Dashboard lists them and apps resume from them.
 * Spec: docs/superpowers/specs/2026-07-08-generation-jobs-design.md
 *
 * `app` / `type` are deliberately plain strings (not mirrored unions):
 * every new generation app adds values, and the server validates them
 * (app allowlist + registered job type) — don't "tighten" these here.
 */

export type JobStatus = "queued" | "running" | "complete" | "complete_with_errors" | "failed";
export type JobItemStatus = "pending" | "running" | "complete" | "failed";

export type Job = {
  id: string;
  createdAt: string;
  updatedAt: string;
  finishedAt: string | null;
  brandId: string;
  userId: string | null;
  productId: string | null;
  app: string;
  type: string;
  status: JobStatus;
  title: string;
  payload: Record<string, unknown>;
  totalCount: number;
  doneCount: number;
  errorCount: number;
  error: string | null;
};

export type JobItem = {
  id: string;
  jobId: string;
  idx: number;
  label: string;
  status: JobItemStatus;
  attempts: number;
  input: Record<string, unknown>;
  /** Best-effort shape — matches the b-roll executor's return today. The
   *  server stores untyped jsonb (executors return Record<string, unknown>),
   *  so new executors can extend this; treat fields as optional. */
  output: {
    url?: string;
    model?: string;
    durationMs?: number;
    generationId?: string | null;
    fallbackFrom?: string;
  } | null;
  error: string | null;
  startedAt: string | null;
  finishedAt: string | null;
};

/** Creates + immediately starts a job; payload should snapshot the app session so the page can restore from it. */
export function createJob(args: {
  app: string;
  type: string;
  brandId: string;
  productId?: string | null;
  title: string;
  payload: Record<string, unknown>;
  items: Array<{ label: string; input: Record<string, unknown> }>;
}): Promise<{ job: Job }> {
  return post<{ job: Job }>("/api/jobs", args);
}

export function listJobs(brandId: string): Promise<{ jobs: Job[]; runningCount: number }> {
  return get<{ jobs: Job[]; runningCount: number }>(`/api/jobs?brandId=${encodeURIComponent(brandId)}`);
}

export function getJob(id: string): Promise<{ job: Job; items: JobItem[] }> {
  return get<{ job: Job; items: JobItem[] }>(`/api/jobs/${id}`);
}

export function retryJobItem(jobId: string, itemId: string): Promise<{ ok: true }> {
  return post<{ ok: true }>(`/api/jobs/${jobId}/items/${itemId}/retry`, {});
}

// ---------- Static Ad References ----------

export type StaticAdDeconstructionStatus = "pending" | "running" | "complete" | "failed";

export type StaticAdReference = {
  id: string;
  createdAt: string;
  title: string;
  niche: string;
  imageUrl: string;
  thumbnailUrl: string | null;
  sourcePath: string | null;
  sourceSignature: string | null;
  deconstruction: Record<string, unknown> | null;
  deconstructionStatus: StaticAdDeconstructionStatus;
  deconstructionError: string | null;
  deconstructionGeneratedAt: string | null;
  promptVersion: string | null;
  model: string | null;
};

export function listStaticAdReferences(): Promise<{ references: StaticAdReference[] }> {
  return get<{ references: StaticAdReference[] }>("/api/static-ad-references");
}

export function rescanStaticAdReferences(): Promise<{ ok: true; ingested: number; ids: string[] }> {
  return post<{ ok: true; ingested: number; ids: string[] }>(
    "/api/static-ad-references/rescan",
    {},
  );
}

export function getStaticAdReference(id: string): Promise<{ reference: StaticAdReference }> {
  return get<{ reference: StaticAdReference }>(`/api/static-ad-references/${id}`);
}

export function createStaticAdReference(args: {
  imageUrl?: string;
  dataUrl?: string;
  filename?: string;
  title?: string;
  niche: string;
}): Promise<{ reference: StaticAdReference }> {
  return post<{ reference: StaticAdReference }>("/api/static-ad-references", args);
}

export async function updateStaticAdReference(
  id: string,
  patch: { title?: string; niche?: string },
): Promise<{ reference: StaticAdReference }> {
  const res = await fetch(`/api/static-ad-references/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
  const payload = (await res.json().catch(() => ({}))) as { reference: StaticAdReference } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { reference: StaticAdReference };
}

export function retriggerStaticAdDeconstruction(id: string): Promise<{ ok: true }> {
  return post<{ ok: true }>(`/api/static-ad-references/${id}/deconstruct`, {});
}

export type StaticAdRecreationResult = {
  url: string;
  referenceId: string;
  durationMs: number;
  model: string;
  promptVersion: string;
};

export type StaticAdRecreationBrand = {
  name: string;
  websiteUrl?: string;
  logoUrl?: string | null;
  /**
   * The brand's full 8-section guidelines markdown — the single source
   * of truth. Server uses this directly as the brand context block for
   * the image prompt. Legacy fields below are a fallback for brands
   * scraped before the migration.
   */
  guidelinesMarkdown?: string | null;
  /** @deprecated legacy fields — used only when guidelinesMarkdown is missing. */
  description?: string;
  /** @deprecated */
  tone?: string;
  /** @deprecated */
  colorPalette?: Array<{ name: string; hex: string; usage: string }>;
  /** @deprecated */
  fonts?: Array<{ name: string; usage: string; weight: string }>;
};

export function recreateStaticAd(args: {
  productId: string;
  angleName: string;
  language?: string;
  referenceId: string;
  brand?: StaticAdRecreationBrand | null;
  feedback?: string;
  /**
   * URL of the most-recent generated output for this reference. When set
   * alongside `feedback`, the server switches into feedback-edit mode:
   * instead of re-running the full recreate pipeline from the reference ad,
   * it edits the previous output using nano-banana-pro/edit with the
   * feedback text as the primary instruction. Cuts cost + latency roughly
   * in half and produces results that feel like an iteration on the user's
   * approved direction rather than a fresh roll of the dice.
   */
  previousOutputUrl?: string;
  /**
   * Ad Pipeline linkage. When set, the server logs it into the recreate
   * generation's `inputs` so the originating pipeline card can resolve its
   * latest draft. Never affects the rendered prompt.
   */
  pipelineCardId?: string;
}): Promise<StaticAdRecreationResult> {
  return post<StaticAdRecreationResult>("/api/static-ads/recreate", args);
}

export async function deleteStaticAdReference(id: string): Promise<{ ok: true }> {
  const res = await fetch(`/api/static-ad-references/${id}`, { method: "DELETE" });
  const payload = (await res.json().catch(() => ({}))) as { ok: true } | ApiError;
  if (!res.ok) {
    const msg = (payload as ApiError)?.error ?? `Request failed: ${res.status}`;
    throw new Error(msg);
  }
  return payload as { ok: true };
}

// ---------- Static Ads Iterations ----------

export type IterationsHeadlinesResponse = {
  headlines: string[];
  model: string;
  promptVersion: string;
  durationMs: number;
};

export type IterationsVariationResponse = {
  url: string;
  model: string;
  promptVersion: string;
  durationMs: number;
};

export function generateIterationsHeadlines(args: {
  sourceImageUrl: string;
  angle: string;
  product?: string;
  feedback?: string;
  existingHeadlines?: string[];
  count?: number;
}): Promise<IterationsHeadlinesResponse> {
  return post<IterationsHeadlinesResponse>("/api/static-ads-iterations/headlines", args);
}

export function generateIterationsVariation(args: {
  sourceImageUrl: string;
  headline: string;
  feedback?: string;
}): Promise<IterationsVariationResponse> {
  return post<IterationsVariationResponse>("/api/static-ads-iterations/variation", args);
}

export function uploadIterationsSource(args: {
  dataUrl: string;
  filename?: string;
}): Promise<{ url: string; filename: string }> {
  return post<{ url: string; filename: string }>("/api/static-ads-iterations/upload-source", args);
}

/**
 * Split a research "messages" artifact (plain text — one message per line, or
 * blank-line separated) into individual messages. Mirrors ClientSharePage.
 */
function splitResearchMessages(content: string): string[] {
  const strip = (s: string) =>
    s.replace(/^\s*([-*•]|\d+[.)])\s+/, "").replace(/^["'“”]+|["'“”]+$/g, "").trim();
  const byBlank = content.split(/\n\s*\n/).map((b) => strip(b.trim())).filter(Boolean);
  if (byBlank.length > 1) return byBlank;
  const byLine = content.split(/\n/).map((l) => strip(l.trim())).filter(Boolean);
  if (byLine.length > 1) return byLine;
  const single = strip(content.trim());
  return single ? [single] : [];
}

function messagesArtifactReady(a: ProductAngle): boolean {
  const art = a.artifacts?.messages;
  return Boolean(art && art.status === "complete" && art.content && art.content.trim());
}

/**
 * Message Testing copy = the product's RESEARCH messages (angle.artifacts.messages),
 * NOT freshly-invented copy. For any selected angle whose research messages haven't
 * been generated yet, we generate them on demand (which persists them back onto the
 * product's research), then read them. When a non-English language is chosen, we
 * translate the exact research messages — no new messages are invented.
 */
export async function generateMessageTestingCopy(args: {
  productId: string;
  angles: ProductAngle[];
  language?: string;
  /** Force-regenerate the research messages even if they already exist (the
   *  per-angle "Regenerate" action). Refreshes the persisted research too. */
  force?: boolean;
}): Promise<{ groups: MessageAngleGroup[] }> {
  const selectedNames = new Set(args.angles.map((a) => a.name));
  let angles = args.angles.filter((a) => selectedNames.has(a.name));

  // 1. Ensure research messages exist for every selected angle (generate + persist).
  //    Force mode regenerates all of them; otherwise only the ones still missing.
  const toGenerate = args.force ? angles.filter((a) => a.id) : angles.filter((a) => !messagesArtifactReady(a) && a.id);
  if (toGenerate.length > 0) {
    // Capture prior generatedAt so a forced regen waits for genuinely NEW output
    // (a stale "complete" status from before the regen must not satisfy the poll).
    const prevAt = new Map(toGenerate.map((a) => [a.name, a.artifacts?.messages?.generatedAt]));
    const targetNames = new Set(toGenerate.map((a) => a.name));
    await Promise.all(
      toGenerate.map((a) => generateAngleArtifact(args.productId, a.id!, "messages").catch(() => {})),
    );
    // Poll until every targeted angle's messages artifact settles (complete/failed).
    for (let i = 0; i < 48; i++) {
      await new Promise((r) => setTimeout(r, 2500));
      const { angles: fresh } = await getProductAngles(args.productId);
      angles = fresh.filter((a) => selectedNames.has(a.name));
      const pending = angles.filter((a) => {
        if (!targetNames.has(a.name)) return false;
        const art = a.artifacts?.messages;
        if (!art) return true;
        if (art.status === "failed") return false;
        if (art.status === "complete") {
          const prev = prevAt.get(a.name);
          return prev ? art.generatedAt === prev : false; // forced regen: wait for a new timestamp
        }
        return true; // running / not started yet
      });
      if (pending.length === 0) break;
    }
  }

  // 2. Build the groups straight from the research messages.
  let groups: MessageAngleGroup[] = angles
    .map((a) => ({ name: a.name, messages: splitResearchMessages(a.artifacts?.messages?.content ?? "") }))
    .filter((g) => g.messages.length > 0);

  if (groups.length === 0) {
    throw new Error(
      "No research messages available for the selected angles — generate them from the product's research first.",
    );
  }

  // 3. Translate the exact research messages when a non-English language is chosen.
  const language = (args.language ?? "English").trim();
  if (language.toLowerCase() !== "english") {
    const text = groups.map((g) => `Angle: ${g.name}\n${g.messages.join("\n")}`).join("\n\n");
    const meta = await generateText("translate_messages", { messages: text, language });
    const translated = parseMessagesByAngle(meta.text);
    groups = groups.map((g) => {
      const t = translated.find((p) => p.name === g.name);
      return t && t.messages.length > 0 ? t : g;
    });
  }

  return { groups };
}

// ---------- Listicle Builder ----------

export type ListicleStatus =
  | "drafting" | "analyzing" | "images" | "rendering" | "ready" | "deployed" | "failed";

/**
 * Structured marketing-angle JSON extracted from an uploaded winning ad
 * by the ad_extract_angle prompt. Used to prime the listicle copy
 * generator so the first sections of the lander mirror the ad's pitch.
 */
export type WinningAdAnalysis = {
  primary_angle_name?: string;
  hook?: string;
  mechanism?: string;
  target_pain?: string;
  key_claims?: string[];
  tone?: string;
  creative_format?: string;
  summary?: string;
};

export type ListicleRow = {
  id: string;
  createdAt: string;
  updatedAt: string;
  brandId: string;
  productId: string;
  source: "generate" | "paste" | "winning_ad";
  status: ListicleStatus;
  angleName: string | null;
  language: string;
  destinationUrl: string | null;
  offerExtract: Record<string, unknown> | null;
  copyMarkdown: string | null;
  guidance: string | null;
  renderedHtml: string | null;
  htmlFeedback: string | null;
  landerlabLanderId: string | null;
  landerlabVariantId: string | null;
  landerlabEncryptedVariantId: string | null;
  landerlabDomainId: string | null;
  publishedUrl: string | null;
  previewUrl: string | null;
  editorUrl: string | null;
  // Winning-ad workflow: populated after POST /:id/analyze-ad. null
  // for source === "generate" | "paste".
  winningAdUrl: string | null;
  winningAdType: "video" | "static" | null;
  winningAdTranscript: string | null;
  winningAdAnalysis: WinningAdAnalysis | null;
  error: string | null;
};

export type ListicleImageRow = {
  id: string;
  createdAt: string;
  listicleId: string;
  sectionIdx: number;
  sectionHeadline: string | null;
  imagePrompt: string | null;
  imageUrl: string | null;
  imageStatus: "idle" | "generating" | "ready" | "failed";
  imageApproval: "pending" | "approved" | "rejected";
  imageFeedback: string | null;
  imageError: string | null;
};

export function createListicle(args: {
  brandId: string;
  productId: string;
  source: "generate" | "paste" | "winning_ad";
  language?: string;
  destinationUrl?: string;
  angleName?: string;
  copyMarkdown?: string;
  guidance?: string;
}): Promise<{ listicle: ListicleRow }> {
  return post<{ listicle: ListicleRow }>("/api/listicles", args);
}

export function getListicle(id: string): Promise<{ listicle: ListicleRow; images: ListicleImageRow[] }> {
  return get<{ listicle: ListicleRow; images: ListicleImageRow[] }>(`/api/listicles/${id}`);
}

export async function patchListicle(
  id: string,
  patch: Partial<Pick<ListicleRow, "copyMarkdown" | "angleName" | "guidance" | "destinationUrl" | "htmlFeedback" | "language">> & {
    // Winning-ad analysis is the editable preview the user can tweak
    // before generating the listicle copy. Server validates the shape;
    // here we accept the partial type so the UI can patch individual
    // fields one at a time.
    winningAdAnalysis?: WinningAdAnalysis;
  },
): Promise<{ listicle: ListicleRow }> {
  const res = await fetch(`/api/listicles/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
  const payload = (await res.json().catch(() => ({}))) as { listicle: ListicleRow } | ApiError;
  if (!res.ok) throw new Error((payload as ApiError)?.error ?? `Request failed: ${res.status}`);
  return payload as { listicle: ListicleRow };
}

/**
 * Upload a winning paid-social ad (video .mp4/.mov or static .jpg/.png)
 * for analysis. Server:
 *   1. Decodes the base64 dataUrl, uploads to fal.storage.
 *   2. Video → fal whisper transcript → ad_extract_angle prompt with the
 *      transcript.  Static → ad_extract_angle prompt with the image
 *      attached via Claude vision.
 *   3. Persists winningAdUrl / winningAdType / winningAdTranscript /
 *      winningAdAnalysis on the listicle row.
 * Returns the analysis + transcript so the UI can show an editable
 * review before the user triggers copy generation.
 */
export function analyzeListicleAd(
  id: string,
  args: { dataUrl: string; filename: string },
): Promise<{
  adUrl: string;
  adType: "video" | "static";
  transcript: string | null;
  analysis: WinningAdAnalysis;
}> {
  return post<{
    adUrl: string;
    adType: "video" | "static";
    transcript: string | null;
    analysis: WinningAdAnalysis;
  }>(`/api/listicles/${id}/analyze-ad`, args);
}

export function extractListicleOffer(id: string): Promise<{ offer: Record<string, unknown> }> {
  return post<{ offer: Record<string, unknown> }>(`/api/listicles/${id}/extract-offer`, {});
}

export function generateListicleCopy(
  id: string,
  args: { feedback?: string } = {},
): Promise<{ copyMarkdown: string }> {
  return post<{ copyMarkdown: string }>(`/api/listicles/${id}/generate-copy`, args);
}

export function generateListicleImagePrompts(id: string): Promise<{ images: ListicleImageRow[] }> {
  return post<{ images: ListicleImageRow[] }>(`/api/listicles/${id}/generate-image-prompts`, {});
}

export function generateListicleImage(
  id: string,
  imageId: string,
  feedback?: string,
): Promise<{ image: ListicleImageRow }> {
  return post<{ image: ListicleImageRow }>(`/api/listicles/${id}/images/${imageId}/generate`, feedback ? { feedback } : {});
}

export async function patchListicleImage(
  id: string,
  imageId: string,
  patch: Partial<Pick<ListicleImageRow, "imageApproval" | "imageFeedback">>,
): Promise<{ image: ListicleImageRow }> {
  const res = await fetch(`/api/listicles/${id}/images/${imageId}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
  const payload = (await res.json().catch(() => ({}))) as { image: ListicleImageRow } | ApiError;
  if (!res.ok) throw new Error((payload as ApiError)?.error ?? `Request failed: ${res.status}`);
  return payload as { image: ListicleImageRow };
}

export function renderListicleHtml(id: string): Promise<{ renderedHtml: string }> {
  return post<{ renderedHtml: string }>(`/api/listicles/${id}/render-html`, {});
}

export function deployListicle(id: string): Promise<{
  publishedUrl: string;
  previewUrl: string;
  editorUrl: string;
  slug: string;
}> {
  return post<{ publishedUrl: string; previewUrl: string; editorUrl: string; slug: string }>(
    `/api/listicles/${id}/deploy`,
    {},
  );
}

// ---------- Ad Creative Console ----------
//
// Typed wrappers over /api/ad-console/* (managers + admins, any brand). The
// types mirror the server rows verbatim, with the JSON-wire caveats: timestamps
// and `numeric` score columns arrive as strings, `integer` columns as numbers,
// and `jsonb` columns as their parsed shape. Every endpoint 401s when
// unauthenticated and the credit-spending pulls 424 when Apify isn't configured.

const AD_CONSOLE = "/api/ad-console";

/**
 * Route an organic thumbnail through our same-origin image proxy. Instagram's
 * CDN serves covers with CORP `same-origin`, so a direct <img> renders black;
 * the proxy re-serves the bytes from our origin. Pass-through for empty URLs.
 */
export function adConsoleImg(url: string | null | undefined): string | undefined {
  if (!url) return undefined;
  return `${AD_CONSOLE}/img?url=${encodeURIComponent(url)}`;
}

/** Shared niche_streams row — the broad-query/seed config for a niche. */
export type AdConsoleNicheStream = {
  id: string;
  createdAt: string;
  updatedAt: string;
  niche: string;
  displayName: string;
  keywords: { adLibrary?: string[]; organic?: string[]; hashtags?: string[] } | null;
  leadingAdvertisers: Array<{
    name: string;
    fbPageUrl?: string;
    fbPageId?: string;
    igHandle?: string;
    tiktokHandle?: string;
  }> | null;
  painPointKeywords: string[] | null;
  config: Record<string, unknown> | null;
  lastRefreshedAt: string | null;
};

export type AdConsoleNicheState = {
  nicheType: string | null;
  seeded: boolean;
  stream: AdConsoleNicheStream | null;
};

export type AdConsoleNicheClassification = {
  niche: string;
  confidence: number;
  reasoning: string;
  seeded: boolean;
};

/** Background "make the brand Console-ready" summary (niche + competitors + keywords). */
export type AdConsoleBootstrapResult = {
  brandId: string;
  niche: string | null;
  seeded: boolean;
  competitorCount: number;
  competitorsDiscovered: number;
  keywords: { totalAngles: number; extracted: number; failed: number } | null;
  steps: {
    niche: "ok" | "skipped" | "failed";
    competitors: "ok" | "skipped" | "failed";
    keywords: "ok" | "skipped" | "failed";
  };
  errors: string[];
};

export type AdConsoleCompetitor = {
  id: string;
  createdAt: string;
  updatedAt: string;
  brandId: string;
  name: string;
  fbPageUrl: string | null;
  fbPageId: string | null;
  igHandle: string | null;
  tiktokHandle: string | null;
  source: "auto" | "manual";
  status: "active" | "archived" | string;
  discoveryReason: string | null;
  dedupeKey: string;
  createdBy: string | null;
};

export type AdConsoleKeywordSetStatus = "pending" | "running" | "complete" | "failed";

export type AdConsoleKeywordSet = {
  id: string;
  createdAt: string;
  updatedAt: string;
  brandId: string;
  productId: string | null;
  angleId: string;
  angleName: string | null;
  problemKeywords: string[] | null;
  outcomeKeywords: string[] | null;
  productKeywords: string[] | null;
  status: AdConsoleKeywordSetStatus;
  error: string | null;
  model: string | null;
  promptVersion: string | null;
};

export type AdConsoleAdCreative = {
  id: string;
  createdAt: string;
  updatedAt: string;
  source: string;
  externalId: string;
  advertiserName: string | null;
  pageId: string | null;
  pageUrl: string | null;
  mediaUrls: string[] | null;
  thumbnailUrl: string | null;
  format: "static" | "video" | string | null;
  copy: string | null;
  cta: string | null;
  landingUrl: string | null;
  adStart: string | null;
  adStop: string | null;
  runtimeDays: number | null;
  isActive: boolean | null;
  variationCount: number | null;
  /** AdSpy real engagement + deep link to the live FB/IG post. */
  shares: number | null;
  likes: number | null;
  deepLinkUrl: string | null;
  /** `numeric` → string on the wire. */
  tractionScore: string | null;
  hook: string | null;
  transcript: string | null;
  nicheStreamId: string | null;
  competitorId: string | null;
  rawJson: unknown;
};

export type AdConsoleOrganicPost = {
  id: string;
  createdAt: string;
  updatedAt: string;
  source: "instagram" | "tiktok" | string;
  externalId: string;
  handle: string | null;
  profileName: string | null;
  postUrl: string | null;
  mediaUrl: string | null;
  thumbnailUrl: string | null;
  caption: string | null;
  hashtags: string[] | null;
  views: number | null;
  likes: number | null;
  comments: number | null;
  shares: number | null;
  /** TikTok saves (collectCount) — the TikTok virality metric. IG has no save count. */
  bookmarks: number | null;
  /** Clip length in seconds. */
  durationSec: number | null;
  postedAt: string | null;
  transcript: string | null;
  format: string;
  /** `numeric` → string on the wire. */
  tractionScore: string | null;
  hook: string | null;
  nicheStreamId: string | null;
  rawJson: unknown;
};

export type AdConsoleFeedItemStatus = "new" | "selected" | "skipped";
export type AdConsoleRail = "competitor_ads" | "trending_organic" | "weekly_ideas";

export type AdConsoleFeedItem = {
  id: string;
  createdAt: string;
  updatedAt: string;
  brandId: string;
  itemType: "ad" | "organic";
  adCreativeId: string | null;
  organicPostId: string | null;
  rail: AdConsoleRail;
  refKey: string;
  /** `numeric` → string on the wire. */
  relevanceScore: string | null;
  compositeScore: string | null;
  matchedKeywords: string[] | null;
  status: AdConsoleFeedItemStatus;
  tier2Enriched: boolean;
};

/** One ranked feed card = the brand's feed_item joined to its pooled row. */
export type AdConsoleFeedCard = {
  item: AdConsoleFeedItem;
  ad: AdConsoleAdCreative | null;
  organic: AdConsoleOrganicPost | null;
};

export type AdConsoleRankSummary = {
  brandId: string;
  niche: string | null;
  seeded: boolean;
  streamId: string | null;
  competitorAds: { considered: number; ranked: number };
  trendingOrganic: { considered: number; ranked: number };
};

/** Per-scope counts from one Apify pull. */
export type AdConsoleIngestResult = {
  queriesRun: number;
  itemsSeen: number;
  inserted: number;
  updated: number;
  skipped: number;
};

export type AdConsoleAdIngestSummary = {
  niche: string | null;
  seeded: boolean;
  nicheAds: AdConsoleIngestResult | null;
  competitorAds: AdConsoleIngestResult | null;
  competitorsPulled: number;
};

export type AdConsoleOrganicIngestSummary = {
  niche: string | null;
  seeded: boolean;
  instagram: AdConsoleIngestResult | null;
  tiktok: AdConsoleIngestResult | null;
};

/** Which recreation app a Creative Brief routes into (spec §11). */
export type AdConsoleRecreationApp = "static_ads_recreator" | "script_rewriting";

/** Normalized Creative Brief emitted on "Make it mine". */
export type AdConsoleCreativeBrief = {
  feedItemId: string;
  sourceType: "ad" | "organic";
  sourceId: string;
  brandId: string;
  productId: string | null;
  niche: string | null;
  format: string;
  suggestedApp: AdConsoleRecreationApp;
  referenceMediaUrls: string[];
  thumbnailUrl: string | null;
  sourceCopy: string | null;
  copy: string | null;
  caption: string | null;
  transcript: string | null;
  hook: string | null;
  cta: string | null;
  landingUrl: string | null;
  advertiserName: string | null;
  tractionBadge: string | null;
  sourceUrl: string | null;
  language: string;
  matchedKeywords: string[];
  brand: {
    id: string;
    name: string;
    websiteUrl: string | null;
    guidelinesMarkdown: string | null;
  };
};

/** "Pull this week's feed" background-run snapshot (one per brand, in-memory). */
type AdConsolePullStepStatus = "pending" | "running" | "complete" | "failed";
type AdConsolePullStep<T> = { status: AdConsolePullStepStatus; summary: T | null; error: string | null };
export type AdConsoleFeedPullRun = {
  brandId: string;
  status: "running" | "complete" | "failed";
  startedAt: string;
  finishedAt: string | null;
  currentStep: "ads" | "organic" | "rank" | null;
  steps: {
    ads: AdConsolePullStep<AdConsoleAdIngestSummary>;
    organic: AdConsolePullStep<AdConsoleOrganicIngestSummary>;
    rank: AdConsolePullStep<AdConsoleRankSummary>;
  };
  error: string | null;
};

// ── Niche ──

export function getAdConsoleNiche(brandId: string): Promise<AdConsoleNicheState> {
  return get<AdConsoleNicheState>(`${AD_CONSOLE}/brands/${brandId}/niche`);
}

/**
 * Fire the background bootstrap: auto-detect niche, auto-research competitors
 * (when the watchlist is empty), and extract angle keywords. LLM-only — no
 * Apify spend. Idempotent + server-deduped, safe to call on every Console load.
 */
export function bootstrapAdConsole(brandId: string): Promise<AdConsoleBootstrapResult> {
  return post<AdConsoleBootstrapResult>(`${AD_CONSOLE}/brands/${brandId}/bootstrap`, {});
}

/** (Re)classify the brand's niche from its products + research. 424 if nothing to classify. */
export function detectAdConsoleNiche(
  brandId: string,
): Promise<{ classification: AdConsoleNicheClassification; state: AdConsoleNicheState }> {
  return post<{ classification: AdConsoleNicheClassification; state: AdConsoleNicheState }>(
    `${AD_CONSOLE}/brands/${brandId}/detect-niche`,
    {},
  );
}

// ── Competitors ──

export function listAdConsoleCompetitors(brandId: string): Promise<{ competitors: AdConsoleCompetitor[] }> {
  return get<{ competitors: AdConsoleCompetitor[] }>(`${AD_CONSOLE}/brands/${brandId}/competitors`);
}

export function addAdConsoleCompetitor(
  brandId: string,
  input: {
    name: string;
    fbPageUrl?: string | null;
    fbPageId?: string | null;
    igHandle?: string | null;
    tiktokHandle?: string | null;
  },
): Promise<{ competitor: AdConsoleCompetitor; created: boolean }> {
  return post<{ competitor: AdConsoleCompetitor; created: boolean }>(
    `${AD_CONSOLE}/brands/${brandId}/competitors`,
    input,
  );
}

/** LLM web_search discovery — only ADDS new competitors. 424 if no products / prompt missing. */
export function discoverAdConsoleCompetitors(
  brandId: string,
): Promise<{ inserted: AdConsoleCompetitor[]; all: AdConsoleCompetitor[]; discovered: number }> {
  return post<{ inserted: AdConsoleCompetitor[]; all: AdConsoleCompetitor[]; discovered: number }>(
    `${AD_CONSOLE}/brands/${brandId}/competitors/discover`,
    {},
  );
}

export async function updateAdConsoleCompetitor(
  id: string,
  patch: {
    name?: string;
    fbPageUrl?: string | null;
    fbPageId?: string | null;
    igHandle?: string | null;
    tiktokHandle?: string | null;
    status?: "active" | "archived" | string;
  },
): Promise<{ competitor: AdConsoleCompetitor }> {
  const res = await fetch(`${AD_CONSOLE}/competitors/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
  const payload = (await res.json().catch(() => ({}))) as { competitor: AdConsoleCompetitor } | ApiError;
  if (!res.ok) throw new ApiCallError(res.status, payload as ApiError);
  return payload as { competitor: AdConsoleCompetitor };
}

export function deleteAdConsoleCompetitor(id: string): Promise<{ ok: true }> {
  return del<{ ok: true }>(`${AD_CONSOLE}/competitors/${id}`);
}

// ── Keyword sets (Phase 2) ──

export function listAdConsoleKeywordSets(brandId: string): Promise<{ keywordSets: AdConsoleKeywordSet[] }> {
  return get<{ keywordSets: AdConsoleKeywordSet[] }>(`${AD_CONSOLE}/brands/${brandId}/keyword-sets`);
}

/** Kick off keyword extraction for ONE angle. Returns the `running` row to poll. */
export function extractAdConsoleKeywords(
  brandId: string,
  args: { productId: string; angleId: string },
): Promise<{ keywordSet: AdConsoleKeywordSet }> {
  return post<{ keywordSet: AdConsoleKeywordSet }>(`${AD_CONSOLE}/brands/${brandId}/keyword-sets`, args);
}

// ── Search-term manager (operator-curated keywords driving the pull) ──

export type AdConsoleSearchLane = "ad" | "organic";
export type AdConsoleSearchTerms = {
  /** Ad-library search terms. */
  ad: string[];
  /** Organic (IG/TikTok) search terms. */
  organic: string[];
  /** True when ≥1 angle keyword set exists — drives the empty-state "Generate" affordance. */
  hasKeywordSets: boolean;
};

/** The brand's effective, operator-editable search terms (materialized from angle keywords). */
export function getAdConsoleKeywords(brandId: string): Promise<AdConsoleSearchTerms> {
  return get<AdConsoleSearchTerms>(`${AD_CONSOLE}/brands/${brandId}/keywords`);
}

/** Add an operator search term to a lane. Returns the updated lists. */
export function addAdConsoleKeyword(
  brandId: string,
  lane: AdConsoleSearchLane,
  keyword: string,
): Promise<AdConsoleSearchTerms> {
  return post<AdConsoleSearchTerms>(`${AD_CONSOLE}/brands/${brandId}/keywords`, { lane, keyword });
}

/** Remove an operator search term from a lane (persists). Returns the updated lists. */
export function removeAdConsoleKeyword(
  brandId: string,
  lane: AdConsoleSearchLane,
  keyword: string,
): Promise<AdConsoleSearchTerms> {
  return del<AdConsoleSearchTerms>(`${AD_CONSOLE}/brands/${brandId}/keywords`, { lane, keyword });
}

/** Generate keyword sets from angles (LLM, no Apify), then materialize search terms. Poll getAdConsoleKeywords. */
export function generateAdConsoleKeywords(brandId: string): Promise<{ started: true }> {
  return post<{ started: true }>(`${AD_CONSOLE}/brands/${brandId}/keywords/generate`, {});
}

/** Force re-extraction from angles (improved prompt) + reset to the fresh terms. Discards manual edits. Poll getAdConsoleKeywords. */
export function regenerateAdConsoleKeywords(brandId: string): Promise<{ started: true }> {
  return post<{ started: true }>(`${AD_CONSOLE}/brands/${brandId}/keywords/regenerate`, {});
}

// ── Ingestion (Phase 3/4) — spends Apify credits, 424 if Apify unconfigured ──

export function ingestAdConsoleAds(
  brandId: string,
  scope: "niche" | "competitors" | "all" = "all",
): Promise<AdConsoleAdIngestSummary> {
  return post<AdConsoleAdIngestSummary>(`${AD_CONSOLE}/brands/${brandId}/ingest-ads`, { scope });
}

export function ingestAdConsoleOrganic(
  brandId: string,
  scope: "instagram" | "tiktok" | "all" = "all",
): Promise<AdConsoleOrganicIngestSummary> {
  return post<AdConsoleOrganicIngestSummary>(`${AD_CONSOLE}/brands/${brandId}/ingest-organic`, { scope });
}

// ── Ranking + feed (Phase 5) ──

/** Deterministic, no-credit re-rank of the brand's eligible pool into feed_items. */
export function rankAdConsoleFeed(brandId: string): Promise<AdConsoleRankSummary> {
  return post<AdConsoleRankSummary>(`${AD_CONSOLE}/brands/${brandId}/rank-feed`, {});
}

export function getAdConsoleFeed(
  brandId: string,
  opts?: { rail?: AdConsoleRail; status?: AdConsoleFeedItemStatus; limit?: number },
): Promise<{ feed: AdConsoleFeedCard[] }> {
  const params = new URLSearchParams();
  if (opts?.rail) params.set("rail", opts.rail);
  if (opts?.status) params.set("status", opts.status);
  if (opts?.limit) params.set("limit", String(opts.limit));
  const qs = params.toString();
  return get<{ feed: AdConsoleFeedCard[] }>(
    `${AD_CONSOLE}/brands/${brandId}/feed${qs ? `?${qs}` : ""}`,
  );
}

// ── Make-it-mine / Skip (Phase 6) ──

export function selectAdConsoleFeedItem(
  brandId: string,
  feedItemId: string,
): Promise<{ brief: AdConsoleCreativeBrief; item: AdConsoleFeedItem }> {
  return post<{ brief: AdConsoleCreativeBrief; item: AdConsoleFeedItem }>(
    `${AD_CONSOLE}/brands/${brandId}/feed/${feedItemId}/select`,
    {},
  );
}

export function skipAdConsoleFeedItem(brandId: string, feedItemId: string): Promise<{ ok: true }> {
  return post<{ ok: true }>(`${AD_CONSOLE}/brands/${brandId}/feed/${feedItemId}/skip`, {});
}

// ── "Pull this week's feed" orchestration (Phase 6) ──

/** Fire the chained ads → organic → rank pull. 424 if Apify unconfigured; poll status below. */
export function startAdConsoleFeedPull(
  brandId: string,
): Promise<{ run: AdConsoleFeedPullRun; alreadyRunning: boolean }> {
  return post<{ run: AdConsoleFeedPullRun; alreadyRunning: boolean }>(
    `${AD_CONSOLE}/brands/${brandId}/pull-feed`,
    {},
  );
}

export function getAdConsoleFeedPullStatus(
  brandId: string,
): Promise<{ run: AdConsoleFeedPullRun | null }> {
  return get<{ run: AdConsoleFeedPullRun | null }>(`${AD_CONSOLE}/brands/${brandId}/pull-feed/status`);
}

// ── This Week's Ideas (LLM-generated rail) ──

export type AdConsoleIdeaSourceRef = { type: string | null; ref: string | null; note: string | null };

/** One LLM-generated ad concept in the "This Week's Ideas" rail. */
export type AdConsoleIdea = {
  id: string;
  createdAt: string;
  updatedAt: string;
  brandId: string;
  batchId: string;
  title: string | null;
  hook: string | null;
  concept: string | null;
  format: "static" | "video" | "ugc" | string | null;
  angle: string | null;
  rationale: string | null;
  sourceRefs: AdConsoleIdeaSourceRef[] | null;
  status: AdConsoleFeedItemStatus;
  model: string | null;
  promptVersion: string | null;
};

export type AdConsoleIdeasSummary = {
  brandId: string;
  batchId: string;
  generated: number;
  grounding: { ads: number; organic: number };
};

/** The brand's newest idea batch. `includeActioned` adds selected/skipped cards. */
export function getAdConsoleIdeas(
  brandId: string,
  opts?: { includeActioned?: boolean },
): Promise<{ ideas: AdConsoleIdea[] }> {
  const qs = opts?.includeActioned ? "?includeActioned=true" : "";
  return get<{ ideas: AdConsoleIdea[] }>(`${AD_CONSOLE}/brands/${brandId}/ideas${qs}`);
}

/** Generate a fresh batch (one LLM call, no Apify credits). 424 if prompt unconfigured. */
export function generateAdConsoleIdeas(
  brandId: string,
  count?: number,
): Promise<{ summary: AdConsoleIdeasSummary; ideas: AdConsoleIdea[] }> {
  return post<{ summary: AdConsoleIdeasSummary; ideas: AdConsoleIdea[] }>(
    `${AD_CONSOLE}/brands/${brandId}/ideas/generate`,
    count != null ? { count } : {},
  );
}

export function selectAdConsoleIdea(brandId: string, ideaId: string): Promise<{ idea: AdConsoleIdea }> {
  return post<{ idea: AdConsoleIdea }>(`${AD_CONSOLE}/brands/${brandId}/ideas/${ideaId}/select`, {});
}

export function skipAdConsoleIdea(brandId: string, ideaId: string): Promise<{ idea: AdConsoleIdea }> {
  return post<{ idea: AdConsoleIdea }>(`${AD_CONSOLE}/brands/${brandId}/ideas/${ideaId}/skip`, {});
}

// ---------- Ad Pipeline ----------

export type AdPipelineStage = "idea" | "in_production" | "ready";

export type AdPipelineCardOutput = {
  source: "asset" | "generation";
  kind: "text" | "image";
  text: string | null;
  imageUrl: string | null;
  savedAssetId: string | null;
  generatedAt: string;
};

export type AdPipelineCard = {
  id: string;
  createdAt: string;
  updatedAt: string;
  brandId: string;
  stage: AdPipelineStage;
  sourceType: "ad" | "organic";
  format: "video" | "static" | string;
  brief: AdConsoleCreativeBrief;
  sourceUrl: string | null;
  originalScript: string | null;
  referenceImageUrl: string | null;
  staticReferenceId: string | null;
  productId: string | null;
  angleName: string | null;
  language: string | null;
  bgJobStatus: "pending" | "running" | "complete" | "failed";
  bgJobError: string | null;
  output: AdPipelineCardOutput | null;
};

const AD_PIPELINE = "/api/ad-pipeline";

export function listAdPipelineCards(brandId: string): Promise<{ cards: AdPipelineCard[] }> {
  return get<{ cards: AdPipelineCard[] }>(`${AD_PIPELINE}/brands/${brandId}/cards`);
}

export function getAdPipelineCard(brandId: string, cardId: string): Promise<{ card: AdPipelineCard }> {
  return get<{ card: AdPipelineCard }>(`${AD_PIPELINE}/cards/${cardId}?brandId=${encodeURIComponent(brandId)}`);
}

export function createAdPipelineCard(
  brandId: string,
  args: { feedItemId: string; mode: "idea" | "recreate"; productId?: string | null; angleName?: string | null; language?: string | null },
): Promise<{ card: AdPipelineCard }> {
  return post<{ card: AdPipelineCard }>(`${AD_PIPELINE}/brands/${brandId}/cards`, args);
}

export function updateAdPipelineCard(
  brandId: string,
  cardId: string,
  patch: { stage?: AdPipelineStage; productId?: string | null; angleName?: string | null; language?: string | null },
): Promise<{ card: AdPipelineCard }> {
  return put<{ card: AdPipelineCard }>(`${AD_PIPELINE}/cards/${cardId}`, { brandId, ...patch });
}

export type AdPipelineJob = { cardId: string; status: "pending" | "running" | "complete" | "failed"; error: string | null };

export function getAdPipelineCardJobStatus(cardId: string): Promise<{ job: AdPipelineJob | null }> {
  return get<{ job: AdPipelineJob | null }>(`${AD_PIPELINE}/cards/${cardId}/job-status`);
}
