/**
 * DESIGN: Studio Control Room — Brand Info
 *
 * Single source of truth: the 8-section brand guidelines markdown document
 * generated by the Brand Guidelines Generator skill (server: prompts/brand_guidelines.md).
 *
 * This page renders the markdown beautifully — color swatches, font previews,
 * voice/tone cards, do's/don'ts grid — not raw markdown. An Edit button
 * reveals the underlying markdown for power users; saves write back to
 * brand.guidelinesMarkdown verbatim. A Regenerate button re-runs the
 * extraction.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Globe, Edit3, Save, RefreshCw, AlertTriangle, Loader2, Upload,
  ImageOff, Sparkles, Palette, Type, MessageCircle, Image as ImageIcon,
  Layers, CheckCircle2, XCircle, Eye, FileText, MousePointer2,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { patchBrand, retriggerBrandResearch, uploadBrandLogoRaw } from "@/lib/api";
import { useBrand } from "@/contexts/BrandContext";

// ── Logo upload widget ────────────────────────────────────────────────
// Unchanged from previous version — same upload-or-paste-URL behavior,
// SVG → PNG conversion happens server-side.
function LogoBox({
  logoUrl,
  onSave,
}: {
  logoUrl: string | null;
  onSave: (val: string) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(logoUrl ?? "");
  const [errored, setErrored] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [uploadNote, setUploadNote] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (!editing) setDraft(logoUrl ?? "");
    setErrored(false);
  }, [logoUrl, editing]);

  const handleFile = async (file: File) => {
    setUploadError(null);
    setUploadNote(null);
    setUploading(true);
    try {
      const dataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(typeof reader.result === "string" ? reader.result : "");
        reader.onerror = () => reject(new Error("Failed to read file"));
        reader.readAsDataURL(file);
      });
      if (!dataUrl) throw new Error("Could not read file");
      const { url, converted } = await uploadBrandLogoRaw(dataUrl, file.name);
      onSave(url);
      setDraft(url);
      setEditing(false);
      if (converted) setUploadNote("Converted SVG → PNG");
      if (fileInputRef.current) fileInputRef.current.value = "";
    } catch (err) {
      setUploadError(err instanceof Error ? err.message : String(err));
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="shrink-0 flex flex-col items-center gap-2">
      <div className="w-24 h-24 rounded-xl border border-white/[0.08] bg-white/[0.02] flex items-center justify-center overflow-hidden relative group">
        {logoUrl && !errored ? (
          <img
            src={logoUrl}
            alt="Brand logo"
            className="max-w-[80%] max-h-[80%] object-contain"
            onError={() => setErrored(true)}
          />
        ) : (
          <ImageOff size={22} className="text-white/20" />
        )}
        <button
          onClick={() => fileInputRef.current?.click()}
          disabled={uploading}
          className="absolute inset-x-0 bottom-0 bg-black/70 text-[9px] font-mono text-white/70 py-1 opacity-0 group-hover:opacity-100 transition-opacity uppercase tracking-wider flex items-center justify-center gap-1 disabled:opacity-100"
        >
          {uploading ? (
            <><Loader2 size={9} className="animate-spin" /> Uploading…</>
          ) : (
            <><Upload size={9} /> {logoUrl ? "Change" : "Upload"}</>
          )}
        </button>
      </div>
      <input
        ref={fileInputRef}
        type="file"
        accept="image/png,image/jpeg,image/webp,image/svg+xml"
        className="hidden"
        onChange={(e) => {
          const f = e.target.files?.[0];
          if (f) void handleFile(f);
        }}
      />
      {!editing && (
        <button
          onClick={() => setEditing(true)}
          className="text-[9px] font-mono text-white/30 hover:text-white/60 underline underline-offset-2 transition-colors"
        >
          or paste URL
        </button>
      )}
      {editing && (
        <div className="w-full min-w-[260px] flex flex-col gap-1.5">
          <div className="flex items-center gap-2">
            <input
              type="text"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder="https://…/logo.png"
              className="flex-1 bg-white/[0.03] border border-cyan-500/30 rounded px-2 py-1 text-[11px] text-white/80 outline-none font-mono"
            />
            <button
              onClick={() => {
                onSave(draft.trim());
                setEditing(false);
              }}
              className="px-2 py-1 rounded text-[10px] font-mono bg-emerald-500/15 text-emerald-400 border border-emerald-500/30"
            >
              Save
            </button>
            <button
              onClick={() => setEditing(false)}
              className="px-2 py-1 rounded text-[10px] font-mono text-white/40 hover:text-white/70 transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      )}
      {uploadNote && <span className="text-[9px] font-mono text-emerald-400/80">{uploadNote}</span>}
      {uploadError && (
        <span className="text-[9px] font-mono text-rose-400/80 text-center max-w-[200px]">{uploadError}</span>
      )}
      {errored && !editing && !uploading && (
        <span className="text-[9px] font-mono text-rose-400/70">Couldn't load logo</span>
      )}
    </div>
  );
}

// ── Markdown utilities (client-side mirror of server/lib/brandGuidelinesParse) ─

/**
 * Pull the lines between a literal heading match and the next heading of
 * the same OR shallower level. Used to slice the 8 top-level sections out
 * of the document for special-case rendering.
 */
function sectionBody(markdown: string, headingExact: string): string {
  const lines = markdown.split(/\r?\n/);
  const headingLevel = (headingExact.match(/^#+/) ?? [""])[0].length;
  const idx = lines.findIndex((l) => l.trim() === headingExact);
  if (idx === -1) return "";
  const endRe = new RegExp(`^#{1,${headingLevel}}\\s`);
  let end = lines.length;
  for (let i = idx + 1; i < lines.length; i++) {
    if (endRe.test(lines[i] ?? "")) { end = i; break; }
  }
  return lines.slice(idx + 1, end).join("\n");
}

type ParsedColor = { name: string; hex: string; usage: string };
type ParsedFont = { name: string; role: string };

function fontFamilyFor(name: string): string {
  const lower = name.toLowerCase();
  if (/(serif|garamond|playfair|cormorant|lora|merriweather|caslon|baskerville|didot)/.test(lower)) {
    return `'${name}', Georgia, serif`;
  }
  if (/(mono|code|jetbrains|menlo|consolas|fira\s*code)/.test(lower)) {
    return `'${name}', 'JetBrains Mono', monospace`;
  }
  return `'${name}', 'Inter', system-ui, sans-serif`;
}

/** Build the Google Fonts link href so the live font preview actually loads. */
function googleFontsHref(fonts: ParsedFont[]): string | null {
  const families = fonts
    .filter((f) => f.name && /^[a-zA-Z0-9\s+-]+$/.test(f.name))
    .map((f) => `family=${encodeURIComponent(f.name.trim().replace(/\s+/g, "+"))}:wght@300;400;500;600;700;800`);
  if (families.length === 0) return null;
  return `https://fonts.googleapis.com/css2?${families.join("&")}&display=swap`;
}

function extractColors(markdown: string): ParsedColor[] {
  const body = sectionBody(markdown, "## 3. Color Palette");
  if (!body.trim()) return [];
  const rows: ParsedColor[] = [];
  const HEX_RE = /#[0-9A-Fa-f]{6}\b/;
  for (const line of body.split(/\r?\n/)) {
    if (!line.trim().startsWith("|")) continue;
    if (/^\|[-:\s|]+\|$/.test(line.trim())) continue;
    if (/^\|\s*color\s*\|/i.test(line.trim())) continue;
    const cells = line.split("|").map((c) => c.trim()).filter((c) => c.length > 0);
    if (cells.length < 2) continue;
    let hex = "";
    for (const c of cells) {
      const hm = c.match(HEX_RE);
      if (hm) { hex = hm[0].toUpperCase(); break; }
    }
    if (!hex) continue;
    rows.push({ name: cells[0] ?? "", hex, usage: cells[cells.length - 1] ?? "" });
  }
  return rows;
}

function extractFonts(markdown: string): ParsedFont[] {
  const headings: { heading: string; role: string }[] = [
    { heading: "### Primary Font", role: "Primary" },
    { heading: "### Secondary Font", role: "Secondary" },
    { heading: "### Accent / Mono Font (optional)", role: "Accent" },
    { heading: "### Accent / Mono Font", role: "Accent" },
  ];
  const seen = new Set<string>();
  const fonts: ParsedFont[] = [];
  for (const { heading, role } of headings) {
    const body = sectionBody(markdown, heading);
    if (!body.trim()) continue;
    const m = body.match(/\*\*([^*]+)\*\*/);
    if (!m) continue;
    const name = (m[1] ?? "").trim();
    if (!name || /^(font|placeholder|tbd|unknown)/i.test(name)) continue;
    if (seen.has(name.toLowerCase())) continue;
    seen.add(name.toLowerCase());
    fonts.push({ name, role });
  }
  return fonts;
}

// ── Design System parser (client-side mirror of brandGuidelinesParse) ──

type ParsedDesignSystem = {
  pageBackground: string | null;
  cta: {
    background: string | null; color: string | null; borderRadius: string | null;
    padding: string | null; fontWeight: string | null; fontTransform: string | null;
    letterSpacing: string | null; border: string | null; boxShadow: string | null;
    hover: string | null;
  };
  card: {
    background: string | null; borderRadius: string | null;
    border: string | null; boxShadow: string | null;
  };
  designDna: string | null;
};

function readField(body: string, label: string): string | null {
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`^[\\s-]*\\*{0,2}${escaped}\\*{0,2}\\s*:\\s*(.+?)\\s*$`, "im");
  const m = body.match(re);
  if (!m || !m[1]) return null;
  let v = m[1].trim().replace(/\s+[—–-]\s+.*$/, "").trim();
  if (!v || /^(tbd|—|–|n\/a|none specified)$/i.test(v)) return null;
  return v;
}

function normalisePx(v: string | null): string | null {
  if (!v) return null;
  const m = v.match(/^(\d+(?:\.\d+)?)\s*(?:px|pixels?)?\s*$/i);
  if (m) return `${m[1]}px`;
  return v;
}

function extractDesignSystem(markdown: string): ParsedDesignSystem {
  const empty: ParsedDesignSystem = {
    pageBackground: null,
    cta: {
      background: null, color: null, borderRadius: null, padding: null,
      fontWeight: null, fontTransform: null, letterSpacing: null,
      border: null, boxShadow: null, hover: null,
    },
    card: { background: null, borderRadius: null, border: null, boxShadow: null },
    designDna: null,
  };
  const root = sectionBody(markdown, "## 9. Design System");
  if (!root.trim()) return empty;
  const pageBg = sectionBody(root, "### Page Background");
  const cta = sectionBody(root, "### Primary CTA Button") || sectionBody(root, "### Primary CTA") || sectionBody(root, "### CTA Button");
  const card = sectionBody(root, "### Cards / Section Containers") || sectionBody(root, "### Cards") || sectionBody(root, "### Section Containers");
  const dna = sectionBody(root, "### Design DNA");
  return {
    pageBackground: readField(pageBg, "Hex"),
    cta: {
      background: readField(cta, "Background"),
      color: readField(cta, "Text color") ?? readField(cta, "Text colour"),
      borderRadius: normalisePx(readField(cta, "Border radius")),
      padding: readField(cta, "Padding"),
      fontWeight: readField(cta, "Font weight"),
      fontTransform: readField(cta, "Font transform"),
      letterSpacing: readField(cta, "Letter spacing"),
      border: readField(cta, "Border"),
      boxShadow: readField(cta, "Box shadow"),
      hover: readField(cta, "Hover"),
    },
    card: {
      background: readField(card, "Background"),
      borderRadius: normalisePx(readField(card, "Border radius")),
      border: readField(card, "Border"),
      boxShadow: readField(card, "Box shadow"),
    },
    designDna: dna.trim() || null,
  };
}

/** YIQ luminance helper — pick black or white text for a colored swatch. */
function readableTextOn(hex: string): string {
  const h = hex.replace(/^#/, "");
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  const yiq = (r * 299 + g * 587 + b * 114) / 1000;
  return yiq >= 140 ? "#1A1A1A" : "#FAFAFA";
}

// ── Section components ────────────────────────────────────────────────

function SectionHeader({ icon: Icon, title }: { icon: React.ComponentType<{ size: number; className?: string }>; title: string }) {
  return (
    <div className="flex items-center gap-2 mb-3">
      <Icon size={14} className="text-cyan-400/70" />
      <h2 className="text-[11px] font-mono text-white/50 uppercase tracking-widest">{title}</h2>
    </div>
  );
}

/** Color palette section — renders the parsed colors as big interactive swatches. */
function ColorPaletteSection({ colors }: { colors: ParsedColor[] }) {
  if (colors.length === 0) return null;
  return (
    <section className="rounded-xl border border-white/[0.06] bg-white/[0.015] p-5">
      <SectionHeader icon={Palette} title="Color Palette" />
      <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
        {colors.map((c, i) => (
          <div key={`${c.hex}-${i}`} className="rounded-lg border border-white/[0.08] overflow-hidden">
            <div
              className="h-24 flex items-end p-3"
              style={{ background: c.hex, color: readableTextOn(c.hex) }}
            >
              <div className="font-mono text-[11px] font-semibold tracking-wider">{c.hex}</div>
            </div>
            <div className="p-3 bg-white/[0.02]">
              <div className="text-sm text-white/80 font-medium">{c.name}</div>
              <div className="text-[11px] text-white/40 font-mono leading-relaxed mt-1">{c.usage}</div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

/** Typography section — pulls the bolded font names + previews the actual font. */
function TypographySection({ fonts, markdown }: { fonts: ParsedFont[]; markdown: string }) {
  if (fonts.length === 0) return null;
  // Pull the body of `## 4. Typography` so the prose / size table beneath
  // the previews still gets rendered (line heights, recommended sizes).
  const typoBody = sectionBody(markdown, "## 4. Typography");
  return (
    <section className="rounded-xl border border-white/[0.06] bg-white/[0.015] p-5">
      <SectionHeader icon={Type} title="Typography" />
      <div className="grid gap-3 mb-5">
        {fonts.map((f) => (
          <div key={`${f.role}-${f.name}`} className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
            <div className="flex items-baseline justify-between mb-2">
              <span className="text-[10px] font-mono text-white/30 uppercase tracking-widest">{f.role}</span>
              <span className="text-[11px] font-mono text-cyan-400/60">{f.name}</span>
            </div>
            <div
              className="text-3xl text-white/90 mb-1 leading-tight"
              style={{ fontFamily: fontFamilyFor(f.name), fontWeight: 600 }}
            >
              The quick brown fox
            </div>
            <div
              className="text-sm text-white/55 leading-relaxed"
              style={{ fontFamily: fontFamilyFor(f.name), fontWeight: 400 }}
            >
              Jumps over the lazy dog. 1 2 3 4 5 6 7 8 9 0.
            </div>
          </div>
        ))}
      </div>
      {/* Render the rest of the Typography section's content (size table,
          line heights, etc.) below the font previews. */}
      <div className="prose-section">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{typoBody}</ReactMarkdown>
      </div>
    </section>
  );
}

/** Voice & Tone section — split We Are / We Are Not into side-by-side cards. */
function VoiceToneSection({ markdown }: { markdown: string }) {
  const body = sectionBody(markdown, "## 6. Voice & Tone");
  if (!body.trim()) return null;
  // Pull the We Are / We Are Not table out if present, render as paired
  // green/red chip rows. Everything else (tone-by-context, writing
  // guidelines) renders via react-markdown.
  const tableRows: { weAre: string; weAreNot: string }[] = [];
  let inWeAreTable = false;
  for (const line of body.split(/\r?\n/)) {
    if (/^\|\s*we are\s*\|\s*we are not\s*\|/i.test(line.trim())) {
      inWeAreTable = true;
      continue;
    }
    if (inWeAreTable) {
      if (/^\|[-:\s|]+\|$/.test(line.trim())) continue;
      if (!line.trim().startsWith("|")) {
        inWeAreTable = false;
        continue;
      }
      const cells = line.split("|").map((c) => c.trim()).filter((c) => c.length > 0);
      if (cells.length >= 2) {
        tableRows.push({ weAre: cells[0] ?? "", weAreNot: cells[1] ?? "" });
      }
    }
  }
  return (
    <section className="rounded-xl border border-white/[0.06] bg-white/[0.015] p-5">
      <SectionHeader icon={MessageCircle} title="Voice & Tone" />
      {tableRows.length > 0 && (
        <div className="grid grid-cols-2 gap-2 mb-5">
          {tableRows.map((row, i) => (
            <div key={i} className="contents">
              <div className="px-3 py-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 text-sm flex items-center gap-2">
                <CheckCircle2 size={14} className="text-emerald-400/70 shrink-0" />
                <span>{row.weAre}</span>
              </div>
              <div className="px-3 py-2 rounded-lg bg-rose-500/10 border border-rose-500/20 text-rose-300 text-sm flex items-center gap-2">
                <XCircle size={14} className="text-rose-400/70 shrink-0" />
                <span>{row.weAreNot}</span>
              </div>
            </div>
          ))}
        </div>
      )}
      {/* Drop the We Are / We Are Not table from the body so we don't
          render it twice. */}
      <div className="prose-section">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {body.replace(/\|\s*we are\s*\|\s*we are not\s*\|[\s\S]*?(?=\n\n|\n###|\Z)/i, "")}
        </ReactMarkdown>
      </div>
    </section>
  );
}

/** Do's & Don'ts section — split into a green / red column grid. */
function DosDontsSection({ markdown }: { markdown: string }) {
  const body = sectionBody(markdown, "## 8. Do's and Don'ts");
  if (!body.trim()) return null;
  const dosBody = sectionBody(body, "### Do's ✅") || sectionBody(body, "### Dos ✅") || sectionBody(body, "### Do's");
  const dontsBody = sectionBody(body, "### Don'ts ❌") || sectionBody(body, "### Donts ❌") || sectionBody(body, "### Don'ts");
  const parseBullets = (b: string): string[] =>
    b.split(/\r?\n/)
      .map((l) => l.replace(/^[-*]\s+/, "").replace(/^[✅❌]\s*/, "").trim())
      .filter((l) => l.length > 0);
  const dos = parseBullets(dosBody);
  const donts = parseBullets(dontsBody);
  if (dos.length === 0 && donts.length === 0) return null;
  return (
    <section className="rounded-xl border border-white/[0.06] bg-white/[0.015] p-5">
      <SectionHeader icon={Layers} title="Do's & Don'ts" />
      <div className="grid md:grid-cols-2 gap-4">
        <div>
          <div className="text-[10px] font-mono text-emerald-400/70 uppercase tracking-widest mb-2 flex items-center gap-2">
            <CheckCircle2 size={12} /> Do
          </div>
          <ul className="space-y-2">
            {dos.map((d, i) => (
              <li key={i} className="px-3 py-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-200 text-sm">
                {d}
              </li>
            ))}
          </ul>
        </div>
        <div>
          <div className="text-[10px] font-mono text-rose-400/70 uppercase tracking-widest mb-2 flex items-center gap-2">
            <XCircle size={12} /> Don't
          </div>
          <ul className="space-y-2">
            {donts.map((d, i) => (
              <li key={i} className="px-3 py-2 rounded-lg bg-rose-500/10 border border-rose-500/20 text-rose-200 text-sm">
                {d}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}

/**
 * Design System section — parses the design tokens out of § 9 and
 * renders a LIVE preview of the brand's button (using the exact
 * radius / padding / shadow / hover behaviour the markdown describes),
 * a card preview, and a page-background swatch. This is what the
 * Listicle Builder + future landing-page tools will use to make
 * cloned pages feel on-brand.
 */
function DesignSystemSection({ markdown, headingFont }: { markdown: string; headingFont: string | null }) {
  const ds = useMemo(() => extractDesignSystem(markdown), [markdown]);
  const hasAnything =
    ds.pageBackground || ds.cta.background || ds.cta.borderRadius ||
    ds.card.background || ds.card.borderRadius || ds.designDna;
  if (!hasAnything) return null;

  const btnBg = ds.cta.background ?? "#000000";
  const btnColor = ds.cta.color ?? "#FFFFFF";
  const btnRadius = ds.cta.borderRadius ?? "8px";
  const btnPadding = ds.cta.padding ?? "14px 28px";
  const btnFontWeight = ds.cta.fontWeight ?? "600";
  const btnTransform = ds.cta.fontTransform ?? "uppercase";
  const btnLetterSpacing = ds.cta.letterSpacing ?? "0.04em";
  const btnBorder = ds.cta.border && ds.cta.border !== "none" ? ds.cta.border : undefined;
  const btnShadow = ds.cta.boxShadow && ds.cta.boxShadow !== "none" ? ds.cta.boxShadow : undefined;
  const cardBg = ds.card.background ?? "#FFFFFF";
  const cardRadius = ds.card.borderRadius ?? "12px";
  const cardBorder = ds.card.border ?? "1px solid rgba(0,0,0,0.06)";
  const cardShadow = ds.card.boxShadow && ds.card.boxShadow !== "none" ? ds.card.boxShadow : undefined;

  return (
    <section className="rounded-xl border border-white/[0.06] bg-white/[0.015] p-5">
      <SectionHeader icon={MousePointer2} title="Design System — live previews" />

      <div className="grid md:grid-cols-2 gap-4 mb-5">
        {/* Page background swatch */}
        {ds.pageBackground && (
          <div className="rounded-lg border border-white/[0.08] overflow-hidden">
            <div
              className="h-20 flex items-end p-3"
              style={{ background: ds.pageBackground, color: readableTextOn(ds.pageBackground) }}
            >
              <div className="font-mono text-[11px] font-semibold tracking-wider">{ds.pageBackground}</div>
            </div>
            <div className="p-3 bg-white/[0.02]">
              <div className="text-sm text-white/80 font-medium">Page Background</div>
              <div className="text-[11px] text-white/40 font-mono leading-relaxed mt-1">Applied to body + full-width sections on cloned pages</div>
            </div>
          </div>
        )}

        {/* Card preview */}
        <div className="rounded-lg border border-white/[0.08] overflow-hidden">
          <div className="h-20 flex items-center justify-center p-3 bg-white/[0.04]">
            <div
              style={{
                background: cardBg,
                borderRadius: cardRadius,
                border: cardBorder,
                boxShadow: cardShadow,
                padding: "12px 18px",
                color: "#1a1a1a",
                fontSize: 12,
                fontWeight: 500,
              }}
            >
              Section / Card
            </div>
          </div>
          <div className="p-3 bg-white/[0.02]">
            <div className="text-sm text-white/80 font-medium">Card / Section Container</div>
            <div className="text-[11px] text-white/40 font-mono leading-relaxed mt-1">
              radius {cardRadius} · {cardBorder !== "none" ? "bordered" : "no border"} · {cardShadow ? "shadow" : "no shadow"}
            </div>
          </div>
        </div>
      </div>

      {/* Live button preview — the actual brand button, hover behaviour wired up */}
      {ds.cta.background && (
        <div className="rounded-lg border border-white/[0.08] overflow-hidden mb-5">
          <div className="px-5 py-8 flex items-center justify-center" style={{ background: ds.pageBackground ?? "#F4F4F4" }}>
            <button
              type="button"
              style={{
                background: btnBg,
                color: btnColor,
                borderRadius: btnRadius,
                padding: btnPadding,
                fontWeight: Number(btnFontWeight) || 600,
                textTransform: btnTransform as React.CSSProperties["textTransform"],
                letterSpacing: btnLetterSpacing,
                border: btnBorder ?? "none",
                boxShadow: btnShadow,
                fontFamily: headingFont ?? "Inter, system-ui, sans-serif",
                cursor: "pointer",
                transition: "filter 0.15s ease, transform 0.08s ease",
              }}
              onMouseEnter={(e) => {
                const hover = (ds.cta.hover ?? "").toLowerCase();
                if (/darken|brightness.*0\.|brightness.*9/.test(hover)) e.currentTarget.style.filter = "brightness(0.9)";
                else if (/lighten|brightness.*1\./.test(hover)) e.currentTarget.style.filter = "brightness(1.08)";
                else if (/scale/.test(hover)) e.currentTarget.style.transform = "scale(1.02)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.filter = "";
                e.currentTarget.style.transform = "";
              }}
            >
              SHOP NOW →
            </button>
          </div>
          <div className="p-3 bg-white/[0.02]">
            <div className="text-sm text-white/80 font-medium">Primary CTA Button</div>
            <div className="text-[11px] text-white/40 font-mono leading-relaxed mt-1">
              {btnBg} / {btnColor} · radius {btnRadius} · padding {btnPadding} · weight {btnFontWeight} · {btnTransform}
              {ds.cta.hover ? ` · hover: ${ds.cta.hover}` : ""}
              {btnShadow ? ` · ${btnShadow}` : " · no shadow"}
            </div>
          </div>
        </div>
      )}

      {/* Design DNA */}
      {ds.designDna && (
        <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
          <div className="text-[10px] font-mono text-white/40 uppercase tracking-widest mb-2">Design DNA</div>
          <div className="text-sm text-white/75 leading-relaxed whitespace-pre-wrap">{ds.designDna}</div>
        </div>
      )}
    </section>
  );
}

/** Generic section that just renders a markdown block via react-markdown. */
function MarkdownSection({
  icon, title, headingExact, markdown,
}: {
  icon: React.ComponentType<{ size: number; className?: string }>;
  title: string;
  headingExact: string;
  markdown: string;
}) {
  const body = sectionBody(markdown, headingExact);
  if (!body.trim()) return null;
  return (
    <section className="rounded-xl border border-white/[0.06] bg-white/[0.015] p-5">
      <SectionHeader icon={icon} title={title} />
      <div className="prose-section">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{body}</ReactMarkdown>
      </div>
    </section>
  );
}

// ── Page ───────────────────────────────────────────────────────────────

export default function BrandInfoPage() {
  const { activeBrand, activeBrandId, refreshBrand } = useBrand();

  const [editing, setEditing] = useState(false);
  const [draftMd, setDraftMd] = useState("");
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [reExtracting, setReExtracting] = useState(false);

  // Re-seed draft when brand changes / markdown updates and not editing.
  useEffect(() => {
    if (!activeBrand) return;
    if (!editing) setDraftMd(activeBrand.guidelinesMarkdown ?? "");
  }, [activeBrand, editing]);

  // Poll while research is running so the page fills in as soon as it lands.
  useEffect(() => {
    if (!activeBrandId) return;
    const s = activeBrand?.researchStatus;
    if (s !== "pending" && s !== "researching") return;
    const t = setInterval(() => { void refreshBrand(activeBrandId); }, 3000);
    return () => clearInterval(t);
  }, [activeBrandId, activeBrand?.researchStatus, refreshBrand]);

  const guidelinesMd = activeBrand?.guidelinesMarkdown ?? "";
  const colors = useMemo(() => extractColors(guidelinesMd), [guidelinesMd]);
  const fonts = useMemo(() => extractFonts(guidelinesMd), [guidelinesMd]);
  const googleHref = useMemo(() => googleFontsHref(fonts), [fonts]);

  // Load the brand's fonts dynamically when the brand changes so the
  // typography previews use the actual font families. Adds a link tag to
  // <head>; removed on unmount / when fonts change.
  useEffect(() => {
    if (!googleHref) return;
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = googleHref;
    document.head.appendChild(link);
    return () => { document.head.removeChild(link); };
  }, [googleHref]);

  const handleSaveLogo = async (logoUrl: string) => {
    if (!activeBrandId) return;
    setSaveError(null);
    try {
      await patchBrand(activeBrandId, { logoUrl });
      await refreshBrand(activeBrandId);
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : String(err));
    }
  };

  const handleSaveMarkdown = async () => {
    if (!activeBrandId) return;
    setSaving(true);
    setSaveError(null);
    try {
      await patchBrand(activeBrandId, { guidelinesMarkdown: draftMd });
      await refreshBrand(activeBrandId);
      setEditing(false);
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : String(err));
    } finally {
      setSaving(false);
    }
  };

  const handleReExtract = async () => {
    if (!activeBrandId) return;
    setReExtracting(true);
    setSaveError(null);
    try {
      await retriggerBrandResearch(activeBrandId);
      // Status will move to researching; polling above takes over.
      await refreshBrand(activeBrandId);
    } catch (err) {
      setSaveError(err instanceof Error ? err.message : String(err));
    } finally {
      setReExtracting(false);
    }
  };

  if (!activeBrand) {
    return (
      <div className="h-full flex items-center justify-center text-white/40 font-mono text-sm">
        Select a brand to view its guidelines.
      </div>
    );
  }

  const status = activeBrand.researchStatus;
  const isRunning = status === "pending" || status === "researching";

  return (
    <div className="max-w-5xl mx-auto py-8 px-4 sm:px-6 space-y-6">
      {/* Header strip */}
      <div className="flex items-start gap-6 rounded-xl border border-white/[0.06] bg-white/[0.015] p-5">
        <LogoBox logoUrl={activeBrand.logoUrl} onSave={handleSaveLogo} />
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <h1 className="text-2xl font-semibold text-white/90 truncate">{activeBrand.name}</h1>
            <StatusPill status={status} />
          </div>
          {activeBrand.brandUrl && (
            <a
              href={activeBrand.brandUrl}
              target="_blank"
              rel="noreferrer"
              className="text-sm text-cyan-400/70 hover:text-cyan-300/90 inline-flex items-center gap-1.5"
            >
              <Globe size={12} />
              {activeBrand.brandUrl.replace(/^https?:\/\//, "").replace(/\/$/, "")}
            </a>
          )}
          {activeBrand.researchError && (
            <div className="mt-3 text-[12px] text-rose-300/90 font-mono flex items-start gap-2">
              <AlertTriangle size={14} className="mt-0.5 shrink-0" />
              <span className="whitespace-pre-wrap">{activeBrand.researchError}</span>
            </div>
          )}
        </div>
        <div className="flex flex-col gap-2">
          <button
            onClick={() => (editing ? handleSaveMarkdown() : setEditing(true))}
            disabled={isRunning || saving}
            className="flex items-center justify-center gap-1.5 px-3 py-1.5 rounded text-[11px] font-mono uppercase tracking-wider border border-white/[0.08] bg-white/[0.03] text-white/70 hover:text-white/90 hover:border-white/20 transition-colors disabled:opacity-40"
          >
            {editing ? (
              saving ? (<><Loader2 size={11} className="animate-spin" /> Saving…</>) : (<><Save size={11} /> Save</>)
            ) : (<><Edit3 size={11} /> Edit Markdown</>)}
          </button>
          {editing && !saving && (
            <button
              onClick={() => { setEditing(false); setDraftMd(guidelinesMd); }}
              className="px-3 py-1.5 rounded text-[11px] font-mono uppercase tracking-wider text-white/40 hover:text-white/70 transition-colors"
            >
              Cancel
            </button>
          )}
          <button
            onClick={handleReExtract}
            disabled={isRunning || reExtracting || !activeBrand.brandUrl}
            className="flex items-center justify-center gap-1.5 px-3 py-1.5 rounded text-[11px] font-mono uppercase tracking-wider border border-cyan-500/30 bg-cyan-500/10 text-cyan-300 hover:bg-cyan-500/20 transition-colors disabled:opacity-40"
            title={!activeBrand.brandUrl ? "No brand URL to research" : undefined}
          >
            {reExtracting || isRunning ? (
              <><Loader2 size={11} className="animate-spin" /> Regenerating…</>
            ) : (
              <><RefreshCw size={11} /> Regenerate</>
            )}
          </button>
        </div>
      </div>

      {saveError && (
        <div className="rounded-lg border border-rose-500/30 bg-rose-500/10 px-4 py-2 text-[12px] text-rose-300 font-mono flex items-center gap-2">
          <AlertTriangle size={13} /> {saveError}
        </div>
      )}

      {/* Edit mode — raw markdown textarea */}
      <AnimatePresence mode="wait">
        {editing ? (
          <motion.div
            key="edit"
            initial={{ opacity: 0, y: -4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="rounded-xl border border-cyan-500/30 bg-white/[0.02] p-4"
          >
            <div className="text-[10px] font-mono text-cyan-400/60 uppercase tracking-widest mb-2 flex items-center gap-1.5">
              <FileText size={11} /> Brand Guidelines Markdown
            </div>
            <textarea
              value={draftMd}
              onChange={(e) => setDraftMd(e.target.value)}
              rows={32}
              spellCheck={false}
              className="w-full bg-black/40 text-white/85 font-mono text-[12px] leading-relaxed border border-white/[0.06] rounded-lg p-3 outline-none resize-y"
            />
            <div className="mt-2 text-[11px] text-white/40 font-mono">
              Save overwrites <code className="text-cyan-400/70">brand.guidelinesMarkdown</code>. Editing here updates the source of truth — every downstream app reads from this document.
            </div>
          </motion.div>
        ) : isRunning ? (
          <motion.div
            key="running"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="rounded-xl border border-white/[0.06] bg-white/[0.015] p-8 text-center"
          >
            <Loader2 size={20} className="animate-spin mx-auto text-cyan-400/70 mb-3" />
            <div className="text-sm text-white/70">Researching brand guidelines…</div>
            <div className="text-[11px] text-white/40 font-mono mt-1">
              Reading {activeBrand.brandUrl ?? "the brand URL"} and synthesising the 8-section style guide.
            </div>
          </motion.div>
        ) : !guidelinesMd ? (
          <motion.div
            key="empty"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="rounded-xl border border-white/[0.06] bg-white/[0.015] p-8 text-center"
          >
            <Sparkles size={20} className="mx-auto text-white/30 mb-3" />
            <div className="text-sm text-white/70 mb-1">No brand guidelines yet</div>
            <div className="text-[11px] text-white/40 font-mono mb-4">
              Click Regenerate to extract the brand's identity from{" "}
              {activeBrand.brandUrl ? (
                <span className="text-cyan-400/70">{activeBrand.brandUrl}</span>
              ) : (
                "the brand URL (you'll need to add one first)"
              )}
              .
            </div>
          </motion.div>
        ) : (
          <motion.div
            key="rendered"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="space-y-4"
          >
            <MarkdownSection icon={Eye} title="Brand Overview" headingExact="## 1. Brand Overview" markdown={guidelinesMd} />
            <MarkdownSection icon={ImageIcon} title="Logo Usage" headingExact="## 2. Logo Usage" markdown={guidelinesMd} />
            <ColorPaletteSection colors={colors} />
            <TypographySection fonts={fonts} markdown={guidelinesMd} />
            <MarkdownSection icon={ImageIcon} title="Imagery" headingExact="## 5. Imagery" markdown={guidelinesMd} />
            <VoiceToneSection markdown={guidelinesMd} />
            <MarkdownSection icon={Layers} title="Applications" headingExact="## 7. Applications" markdown={guidelinesMd} />
            <DosDontsSection markdown={guidelinesMd} />
            <DesignSystemSection markdown={guidelinesMd} headingFont={fonts[0]?.name ?? null} />
          </motion.div>
        )}
      </AnimatePresence>

      {/* prose styling inside .prose-section */}
      <style>{`
        .prose-section { color: rgba(255,255,255,0.75); font-size: 14px; line-height: 1.6; }
        .prose-section h3 { color: rgba(255,255,255,0.85); font-weight: 600; font-size: 14px; margin-top: 18px; margin-bottom: 6px; }
        .prose-section h4 { color: rgba(255,255,255,0.7); font-weight: 600; font-size: 13px; margin-top: 14px; margin-bottom: 4px; }
        .prose-section p { color: rgba(255,255,255,0.65); margin: 6px 0 10px; }
        .prose-section strong { color: rgba(255,255,255,0.9); font-weight: 600; }
        .prose-section em { color: rgba(255,255,255,0.55); }
        .prose-section ul { padding-left: 22px; margin: 6px 0; }
        .prose-section li { margin: 4px 0; color: rgba(255,255,255,0.7); }
        .prose-section a { color: rgb(96, 165, 250); text-decoration: underline; }
        .prose-section table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 12px; }
        .prose-section th { text-align: left; padding: 8px 10px; background: rgba(255,255,255,0.04); color: rgba(255,255,255,0.5); font-weight: 600; font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid rgba(255,255,255,0.08); }
        .prose-section td { padding: 8px 10px; border-bottom: 1px solid rgba(255,255,255,0.04); color: rgba(255,255,255,0.75); }
        .prose-section code { background: rgba(255,255,255,0.06); padding: 1px 6px; border-radius: 3px; font-family: 'JetBrains Mono', monospace; font-size: 12px; }
        .prose-section blockquote { border-left: 2px solid rgba(255,255,255,0.15); padding-left: 12px; color: rgba(255,255,255,0.5); margin: 8px 0; font-style: italic; }
      `}</style>
    </div>
  );
}

function StatusPill({ status }: { status: "pending" | "researching" | "complete" | "failed" }) {
  const cfg = {
    pending: { label: "Pending", color: "bg-white/[0.04] text-white/40 border-white/[0.08]" },
    researching: { label: "Researching", color: "bg-cyan-500/15 text-cyan-300 border-cyan-500/30" },
    complete: { label: "Complete", color: "bg-emerald-500/10 text-emerald-300 border-emerald-500/20" },
    failed: { label: "Failed", color: "bg-rose-500/10 text-rose-300 border-rose-500/30" },
  }[status];
  return (
    <span className={`text-[10px] font-mono uppercase tracking-widest px-2 py-0.5 rounded border ${cfg.color}`}>
      {cfg.label}
    </span>
  );
}
