/**
 * Character Seedance preprocessing pipeline.
 *
 * Seedance 2.0 ref-to-video flags realistic photos as "likeness of real
 * people" and refuses to process them, even when the photo is itself
 * AI-generated by Nano-Banana-Pro / Gemini. The fix is a 2-step Nano-Banana-Pro
 * pre-pass that converts the raw character image into a fully synthetic,
 * AI-styled portrait that passes Seedance's likeness detector while
 * preserving identity:
 *
 *   Step 1 → `character_seedance_turnaround` master prompt produces a
 *            clean turnaround / reference-sheet on a white studio background
 *            (multi-view + close-up panels, neutralized wardrobe, calm
 *            expression). This image reads as "design-board" art rather than
 *            a photo of a real person.
 *
 *   Step 2 → `character_seedance_portrait` master prompt feeds the
 *            turnaround back in and asks for a tight close-up of the face on
 *            a white background. This is the URL we send to Seedance as
 *            `@Image2`.
 *
 * Both intermediate URLs are persisted on the character row so the user can
 * inspect / regenerate either step without losing the other.
 *
 * The worker is idempotent (skips if already complete) and concurrency-gated
 * so backfilling a library of N characters doesn't fan out N parallel
 * fal.ai calls.
 */
import { eq } from "drizzle-orm";
import { db, schema } from "./db.js";
import { generateImage } from "./fal.js";
import { loadPrompt, PromptNotConfiguredError } from "./prompts.js";

const TURNAROUND_ACTION = "character_seedance_turnaround";
const PORTRAIT_ACTION = "character_seedance_portrait";
// Use Nano-Banana-2 (Google's newer fast image editor) for prep — its output
// reads less photo-realistic than Nano-Banana-Pro, which is exactly what we
// need to defeat Seedance's likeness detector.
const NB2_MODEL = "fal-ai/nano-banana-2/edit";

/**
 * Cap inflight Nano-Banana-Pro calls for the prep pipeline. Each prep is two
 * sequential NBP calls (Step 1 → Step 2); this gate limits how many preps run
 * in parallel. Boot-time backfill across many characters trivially blows past
 * fal.ai's per-account rate limits without this.
 */
class Semaphore {
  private inflight = 0;
  private queue: Array<() => void> = [];
  constructor(private readonly limit: number) {}
  async run<T>(fn: () => Promise<T>): Promise<T> {
    if (this.inflight >= this.limit) {
      await new Promise<void>((resolve) => this.queue.push(resolve));
    }
    this.inflight++;
    try {
      return await fn();
    } finally {
      this.inflight--;
      const next = this.queue.shift();
      if (next) next();
    }
  }
}

const prepGate = new Semaphore(2);

async function setStatus(id: string, patch: {
  status?: "pending" | "running" | "complete" | "failed";
  error?: string | null;
  sheetUrl?: string | null;
  portraitUrl?: string | null;
}) {
  const update: Record<string, unknown> = {};
  if (patch.status !== undefined) update.seedancePrepStatus = patch.status;
  if (patch.error !== undefined) update.seedancePrepError = patch.error;
  if (patch.sheetUrl !== undefined) update.seedanceSheetUrl = patch.sheetUrl;
  if (patch.portraitUrl !== undefined) update.seedancePortraitUrl = patch.portraitUrl;
  if (Object.keys(update).length === 0) return;
  await db.update(schema.characters).set(update).where(eq(schema.characters.id, id));
}

/**
 * Run the 2-step prep for a single character row. Idempotent — if the row is
 * already `complete`, returns immediately. If it's `running` from a stale
 * boot, the caller is responsible for deciding whether to retry (boot-time
 * backfill treats `running` as stale-and-retry; the on-upload trigger never
 * re-fires for an in-flight row).
 *
 * Returns true on success, false on any failure (failure is logged + persisted).
 */
export async function prepareCharacterForSeedance(id: string, opts: { force?: boolean } = {}): Promise<boolean> {
  return prepGate.run(async () => {
    const [row] = await db
      .select()
      .from(schema.characters)
      .where(eq(schema.characters.id, id))
      .limit(1);
    if (!row) {
      console.warn(`[character-prep] character ${id} not found`);
      return false;
    }

    if (!opts.force && row.seedancePrepStatus === "complete" && row.seedancePortraitUrl) {
      return true;
    }

    await setStatus(id, { status: "running", error: null });

    try {
      // Step 1 — turnaround sheet. The original character imageUrl is the
      // reference. Output reads as a design-board sheet, not a real photo.
      let sheetPrompt: ReturnType<typeof loadPrompt>;
      try {
        sheetPrompt = loadPrompt(TURNAROUND_ACTION);
      } catch (err) {
        if (err instanceof PromptNotConfiguredError) {
          await setStatus(id, { status: "failed", error: err.message });
          console.warn(`[character-prep] ${TURNAROUND_ACTION} not configured — skipping ${id}`);
          return false;
        }
        throw err;
      }

      const sheet = await generateImage({
        model: sheetPrompt.config.model ?? NB2_MODEL,
        input: {
          prompt: sheetPrompt.rendered,
          image_urls: [row.imageUrl],
          aspect_ratio: "1:1",
          num_images: 1,
          output_format: "jpeg",
        },
      });
      const sheetUrl = sheet.urls[0];
      if (!sheetUrl) throw new Error("Step 1 (turnaround) returned no image URL");

      // Persist the intermediate result before kicking off Step 2 — if Step 2
      // crashes, we still keep the sheet so a manual retry can resume from it.
      await setStatus(id, { sheetUrl });

      // Step 2 — close-up portrait of the face on white background. Feeds the
      // turnaround sheet back in as the reference. This is what Seedance gets.
      let portraitPrompt: ReturnType<typeof loadPrompt>;
      try {
        portraitPrompt = loadPrompt(PORTRAIT_ACTION);
      } catch (err) {
        if (err instanceof PromptNotConfiguredError) {
          await setStatus(id, { status: "failed", error: err.message });
          console.warn(`[character-prep] ${PORTRAIT_ACTION} not configured — skipping ${id}`);
          return false;
        }
        throw err;
      }

      const portrait = await generateImage({
        model: portraitPrompt.config.model ?? NB2_MODEL,
        input: {
          prompt: portraitPrompt.rendered,
          image_urls: [sheetUrl],
          aspect_ratio: "1:1",
          num_images: 1,
          output_format: "jpeg",
        },
      });
      const portraitUrl = portrait.urls[0];
      if (!portraitUrl) throw new Error("Step 2 (portrait) returned no image URL");

      await setStatus(id, {
        status: "complete",
        portraitUrl,
        error: null,
      });

      console.log(`[character-prep] ${id} → sheet+portrait ready`);
      return true;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[character-prep] ${id} failed:`, err);
      await setStatus(id, { status: "failed", error: msg });
      return false;
    }
  });
}

/**
 * Find every character row whose Seedance prep is missing or failed and queue
 * each one through `prepareCharacterForSeedance`. Returns the list of ids
 * queued. Designed to be called once on boot — concurrency is bounded by the
 * internal semaphore.
 *
 * Note: rows with status="running" are treated as stale (a previous boot
 * crashed mid-flight) and re-queued.
 */
export async function backfillCharacterSeedancePrep(): Promise<string[]> {
  const rows = await db
    .select({ id: schema.characters.id, status: schema.characters.seedancePrepStatus, portraitUrl: schema.characters.seedancePortraitUrl })
    .from(schema.characters);

  const queued: string[] = [];
  for (const r of rows) {
    const needsPrep = r.status !== "complete" || !r.portraitUrl;
    if (!needsPrep) continue;
    queued.push(r.id);
    void prepareCharacterForSeedance(r.id);
  }
  return queued;
}
