import { sql } from "drizzle-orm";
import { boolean, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const generations = pgTable("generations", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  action: text("action").notNull(),
  kind: text("kind").notNull(), // "text" | "image" | "video"
  inputs: jsonb("inputs").notNull(),
  output: jsonb("output"),
  model: text("model"),
  promptVersion: text("prompt_version"),
  tokensIn: integer("tokens_in"),
  tokensOut: integer("tokens_out"),
  costUsd: numeric("cost_usd", { precision: 10, scale: 6 }),
  durationMs: integer("duration_ms"),
  error: text("error"),
});

/**
 * A brand is the top-level data-scoping unit. Every product and brand asset
 * belongs to exactly one brand. `research` is the JSON returned by the
 * `brand_extract` master prompt — same shape the client-side BrandIdentity
 * used to persist to localStorage, but now server-backed.
 */
export const brands = pgTable("brands", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  name: text("name").notNull(),
  brandUrl: text("brand_url"),
  logoUrl: text("logo_url"),
  /**
   * Single source of truth for the brand identity. The markdown document
   * generated by the Brand Guidelines Generator skill (see
   * prompts/brand_guidelines.md) — 8 sections: Overview, Logo Usage,
   * Color Palette, Typography, Imagery, Voice & Tone, Applications, Do's
   * & Don'ts. Rendered as-is in the BrandInfoPage UI and injected into
   * every downstream creative tool's prompt (static ads, message
   * testing, listicle copy rewriter, B-roll regen plans, etc.). Replaces
   * the older `research` JSONB field; programmatic consumers that
   * legitimately need hex codes or font names (e.g. the listicle HTML
   * renderer's CSS variables) read them via server/lib/brandGuidelinesParse.ts
   * which deterministically reads the labelled sections of this markdown.
   */
  guidelinesMarkdown: text("guidelines_markdown"),
  /**
   * Retained for backward-compatibility during the migration window —
   * existing brands keep their old JSON until the boot-time backfill
   * regenerates them as markdown. New consumers MUST NOT read this field;
   * read guidelinesMarkdown instead.
   * @deprecated use guidelinesMarkdown
   */
  research: jsonb("research"),
  researchStatus: text("research_status").notNull().default("pending"), // pending | researching | complete | failed
  researchError: text("research_error"),
  /**
   * Future-proofing for multi-team. Today the platform runs as a single
   * team; every brand is owned by the bootstrap "Default Team". Migrating
   * to true multi-team later means filtering existing endpoints by
   * `team_id` — no schema change needed at that point. NULL is tolerated
   * during the migration window for legacy rows that predate teams; the
   * boot-time backfill assigns them to the first team.
   */
  teamId: uuid("team_id"),
  /**
   * Marks this brand as a Done-For-You client. Only DFY-flagged brands expose
   * the Client Console (share links + feedback triage) in the workspace
   * — non-DFY brands are internal/agency-owned and never get a client-facing
   * share surface. Toggled by an admin in Settings → Clients. Default false so
   * a freshly created brand is internal until explicitly promoted.
   */
  isDfyClient: boolean("is_dfy_client").notNull().default(false),
  /**
   * Ad Creative Console niche classification. Auto-detected on setup by
   * classifying the brand's products (e.g. "skincare" vs "supplement") so the
   * brand can be attached to the matching shared `niche_streams` row. NULL =
   * not yet classified; the Console prompts the operator (or runs the
   * classifier) before its first feed pull. Free text, not an enum, so adding a
   * niche is a config-only change.
   */
  nicheType: text("niche_type"),
  /**
   * Ad Console operator-curated search terms. Once materialized (seeded from the
   * brand's angle keyword sets), this becomes the SOURCE OF TRUTH for the search
   * queries the weekly pull issues — the operator can add/remove terms in the
   * Console for full transparency and control. NULL = not yet materialized;
   * buildBrandSearchQueries then falls back to deriving from the keyword sets.
   * Shape: { ad: string[]; organic: string[] } — the two lanes searched
   * (ad-library vs organic).
   */
  searchTerms: jsonb("search_terms"),
  /**
   * Real, client-supplied font FILES for this brand — the actual typefaces
   * named in the Typography section of `guidelinesMarkdown`, hosted on
   * fal.storage. NULL (the default) means "no uploaded files — fall back to
   * the closest Google/web font by name", which is how every brand behaves
   * until a client sends their real font files.
   *
   * Shape: BrandFontFace[] (see server/lib/brandFonts.ts). Each entry pairs a
   * CSS family name with its regular (+ optional italic) file URL and a
   * generic fallback. Consumed by the listicle HTML renderer, which emits
   * `@font-face` rules from these so landers render in the genuine typeface
   * (image-model surfaces like static ads can only reference the font by
   * NAME — they cannot load a file — so those keep using the family name).
   */
  brandFonts: jsonb("brand_fonts"),
});

export const products = pgTable("products", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  name: text("name").notNull(),
  category: text("category").notNull().default("Uncategorized"),
  productUrl: text("product_url"),
  factSheet: text("fact_sheet"),
  productImageUrl: text("product_image_url"),
  productBackImageUrl: text("product_back_image_url"),
  contentImageUrl: text("content_image_url"),
  research: jsonb("research"),
  researchStatus: text("research_status").notNull().default("pending"), // pending | researching | complete | failed
  researchError: text("research_error"),
  /**
   * Phase 2 client share link. A nullable, unique token granting read-only
   * PUBLIC access to this product's research via /share/:token (served by
   * GET /api/share/:token, no auth). NULL = not shared. Revoking sets it back
   * to NULL and rotating overwrites it — either instantly invalidates the old
   * URL. Unique so the public route can resolve a product by token; Postgres
   * treats multiple NULLs as distinct, so unshared products never collide.
   */
  shareToken: text("share_token").unique(),
});

/**
 * Phase 3 client feedback. One row per (share token × section anchor) — the
 * client's structured response to a single feedback target: an angle, its
 * messages, or its ad copy. Written by the PUBLIC, token-gated share page
 * (PUT /api/share/:token/feedback/:anchorId); read by the operator on the
 * product page (GET /api/products/:id/feedback). One-way by design: the client
 * submits an Approve / Needs-changes verdict plus an optional note, and the
 * operator triages it (`status` open|resolved). No operator reply is ever
 * surfaced back on the share page.
 *
 * The unique (share_token, anchor_id) index turns a resubmission into an
 * upsert, so a client can change their mind on a section without piling up
 * duplicate rows. `angleId`, `angleName`, and `sectionKind` are denormalized
 * snapshots captured at submit time so the operator inbox stays readable even
 * if the underlying research is later edited or regenerated. `anchorId` is the
 * exact handle the client checklist (and inline operator annotations) use:
 * `angle-<id>`, `angle-<id>-messages`, or `angle-<id>-adCopy`.
 */
export const shareFeedback = pgTable("share_feedback", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  productId: uuid("product_id").notNull(),
  shareToken: text("share_token").notNull(),
  anchorId: text("anchor_id").notNull(),
  angleId: text("angle_id").notNull(),
  angleName: text("angle_name"),
  sectionKind: text("section_kind").notNull(), // "angle" | "messages" | "adCopy"
  verdict: text("verdict").notNull(), // "approved" | "changes"
  note: text("note"),
  clientName: text("client_name"),
  status: text("status").notNull().default("open"), // open | resolved
  // Phase 4 — AI revision suggestion for "changes" verdicts on text artifacts
  // (messages | adCopy). The operator asks the model to revise the section to
  // address `note`; the proposal is stashed here pending accept/reject.
  suggestion: text("suggestion"), // the AI-proposed revised content (null until generated)
  suggestionStatus: text("suggestion_status"), // null | "ready" | "applied" | "declined" | "failed"
  suggestionError: text("suggestion_error"), // error string when suggestionStatus = "failed"
  // Snapshot of the live copy at the moment the revision was generated, so the
  // operator can see the exact before→after change after the client applies it.
  suggestionOriginal: text("suggestion_original"),
}, (t) => ({
  uniqTokenAnchor: uniqueIndex("share_feedback_token_anchor_uniq").on(t.shareToken, t.anchorId),
}));

export type ShareFeedback = typeof shareFeedback.$inferSelect;
export type NewShareFeedback = typeof shareFeedback.$inferInsert;

/**
 * Approved generated assets that the user has promoted to the shared Brand
 * Assets library. Every app (B-roll, Message Testing, Static Ads, ...) writes
 * here when the user clicks "Save to Brand Assets"; AssetsPage reads here to
 * render the library.
 *
 * `url` points at the fal.ai CDN output (already persistent). We never re-host
 * the bytes — the entry is a pointer + metadata only.
 */
export const brandAssets = pgTable("brand_assets", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  kind: text("kind").notNull(), // "image" | "video" | "document" | "landing_page"
  url: text("url").notNull(),
  thumbnailUrl: text("thumbnail_url"),
  title: text("title").notNull(),
  sourceApp: text("source_app").notNull(), // "broll" | "message_testing" | "static_ads" | ...
  productId: uuid("product_id"), // soft reference to products.id
  metadata: jsonb("metadata"),
  // Author / creator. Auto-captured from req.auth on insert. Nullable so legacy
  // rows (and any future system-generated assets) don't need backfilling.
  userId: uuid("user_id"),
});

/**
 * Static ad reference library. Each row is a single reference ad image,
 * ingested either from `client/public/static-ads/library/<niche>/` on boot or
 * uploaded manually via the API. On creation we fire a background job that
 * runs the `static_ad_deconstruct` master prompt against the image and stores
 * the JSON result in `deconstruction`.
 */
export const staticAdReferences = pgTable("static_ad_references", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  title: text("title").notNull(),
  niche: text("niche").notNull(), // "skincare" | "supplements" | "hair-care" | "other" | ...
  imageUrl: text("image_url").notNull(), // fal.storage URL
  thumbnailUrl: text("thumbnail_url"),
  sourcePath: text("source_path"), // relative path for folder-ingested files, e.g. "skincare/foo.png"
  sourceSignature: text("source_signature"), // `${size}:${mtime}` for ingest dedup
  deconstruction: jsonb("deconstruction"),
  deconstructionStatus: text("deconstruction_status").notNull().default("pending"), // pending | running | complete | failed
  deconstructionError: text("deconstruction_error"),
  deconstructionGeneratedAt: timestamp("deconstruction_generated_at", { withTimezone: true }),
  promptVersion: text("prompt_version"),
  model: text("model"),
});

export type Generation = typeof generations.$inferSelect;
export type NewGeneration = typeof generations.$inferInsert;
export type Brand = typeof brands.$inferSelect;
export type NewBrand = typeof brands.$inferInsert;
export type Product = typeof products.$inferSelect;
export type NewProduct = typeof products.$inferInsert;
export type BrandAsset = typeof brandAssets.$inferSelect;
export type NewBrandAsset = typeof brandAssets.$inferInsert;
export type StaticAdReference = typeof staticAdReferences.$inferSelect;
export type NewStaticAdReference = typeof staticAdReferences.$inferInsert;

/**
 * Character library — reference photos of on-camera subjects for the Character
 * B-roll app. Two-tier ownership:
 *
 *   - `brandId IS NULL`  → default / shared library (every brand sees it).
 *                          Ingested from `client/public/characters/library/*`
 *                          on boot via `characterIngest.ts`.
 *   - `brandId = <uuid>` → brand-private library (only that brand sees it).
 *                          Created via the UI Upload button.
 *
 * The Character B-roll picker reads `?brandId=<id>` and merges both tiers,
 * showing default characters first and brand-private ones second.
 */
export const characters = pgTable("characters", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id"), // NULL = default/shared, set = brand-private
  title: text("title").notNull(),
  imageUrl: text("image_url").notNull(), // fal.storage URL — original (used as input to image-gen pipeline; also the source for Seedance prep)
  thumbnailUrl: text("thumbnail_url"),
  sourcePath: text("source_path"), // relative path for folder-ingested files
  sourceSignature: text("source_signature"), // `${size}:${mtime}` for ingest dedup

  /**
   * Seedance 2.0 ref-to-video flags realistic photos as "likeness of real
   * people" and refuses to process them. The fix is a 2-step Nano-Banana-Pro
   * preprocessing pipeline that converts the raw character photo into a
   * fully synthetic, AI-styled portrait that passes Seedance's likeness
   * detector while preserving the character's identity.
   *
   *   Step 1 → turnaround / reference sheet (multi-view, neutral wardrobe).
   *            Stored in `seedanceSheetUrl` so we can re-derive the close-up
   *            later or use the sheet itself as a richer reference.
   *   Step 2 → close-up portrait of the face on white background. Stored in
   *            `seedancePortraitUrl`. THIS is the URL we pass to Seedance as
   *            the character reference (`@Image2`).
   *
   * `seedancePrepStatus` covers the whole 2-step pipeline:
   *   pending  — never run
   *   running  — in flight
   *   complete — both URLs populated
   *   failed   — at least one step errored; see seedancePrepError
   *
   * The original `imageUrl` is still used as the character reference for
   * Nano-Banana-Pro image generation (NBP accepts realistic photos fine).
   * Only Seedance gets the synthetic version.
   */
  seedanceSheetUrl: text("seedance_sheet_url"),
  seedancePortraitUrl: text("seedance_portrait_url"),
  seedancePrepStatus: text("seedance_prep_status").notNull().default("pending"),
  seedancePrepError: text("seedance_prep_error"),
});

export type Character = typeof characters.$inferSelect;
export type NewCharacter = typeof characters.$inferInsert;

// ──────────────────────────────────────────────────────────────────────────
// AUTH + TEAM
//
// Five tables form the auth + team-management foundation:
//
//   users         — one row per human; canonical login record (email +
//                   bcrypt hash). One user can belong to many teams via
//                   `team_members` (today: just one).
//   sessions      — one row per active login; the random `token` lives in
//                   the user's `dfy_session` httpOnly cookie. Expired or
//                   revoked rows are pruned lazily on validation.
//   teams         — the workspace boundary. v1 ships with exactly one
//                   "Default Team" created on first registration; the
//                   shape is multi-team-ready so future expansion is a
//                   non-breaking change.
//   team_members  — the (team, user) join table with a role per user.
//                   Role is `admin` (full access — can invite, change
//                   roles, remove members) or `member` (read/use access
//                   only).
//   invites       — pending invitations. Admins create one with `email`
//                   + `role`; the row generates a random `token` that
//                   embeds in the invite URL. Accepting consumes the
//                   row (sets `accepted_at`) and creates the user +
//                   team_members rows. Expired invites stay in the
//                   table for audit; pruning is lazy.
// ──────────────────────────────────────────────────────────────────────────

export const users = pgTable("users", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  name: text("name").notNull(),
  avatarUrl: text("avatar_url"),
});

export const sessions = pgTable("sessions", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  userId: uuid("user_id").notNull(),
  token: text("token").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
});

export const teams = pgTable("teams", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  name: text("name").notNull(),
});

export const teamMembers = pgTable("team_members", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  teamId: uuid("team_id").notNull(),
  userId: uuid("user_id").notNull(),
  role: text("role").notNull().default("member"), // admin | member
});

/**
 * Per-user × per-brand access grants.
 *
 * One row per (user, brand) pair = "this user can see this brand in their
 * workspace switcher and use it on every brand-scoped endpoint." Admins are
 * NOT represented here — they implicitly see every brand on their team. We
 * only persist rows for non-admin members so admin-bypass logic stays a
 * single role check rather than a brand-count query.
 *
 * Created when:
 *   - A new brand is created → the creator (if non-admin) gets a row.
 *     Admins get implicit access via role; other teammates get no rows
 *     by default — admin opens "Manage workspaces" to grant access.
 *   - An admin uses the SettingsPage "Manage workspaces" UI to flip a
 *     checkbox on for a specific member.
 *   - Boot-time backfill (one-shot) when this table is first created:
 *     grants every existing non-admin member access to every brand on
 *     their team, so ship doesn't silently lock anyone out.
 *
 * Deleted when:
 *   - Admin un-checks a brand in the modal.
 *   - The brand is deleted (cascade — handled in DELETE /api/brands/:id).
 *   - The user leaves the team (cascade — handled in DELETE team/members).
 */
export const brandMembers = pgTable("brand_members", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  userId: uuid("user_id").notNull(),
  createdBy: uuid("created_by"), // admin who granted access; null = system backfill
}, (t) => ({
  uniqBrandUser: uniqueIndex("brand_members_brand_user_uniq").on(t.brandId, t.userId),
}));

export const invites = pgTable("invites", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  teamId: uuid("team_id").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull().default("member"),
  token: text("token").notNull().unique(),
  invitedByUserId: uuid("invited_by_user_id").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
});

/**
 * Admin-issued password reset. An admin generates a one-time, expiring token for
 * a team member (POST /api/team/members/:userId/reset-password); the admin shares
 * the resulting /reset-password?token=… link, and the user sets a new password
 * (GET/POST /api/auth/reset/:token). No email infra — the link is shared manually,
 * mirroring invites. Single-use (`usedAt`) + short TTL; redeeming it also clears
 * the user's existing sessions so any old logins are invalidated.
 */
export const passwordResets = pgTable("password_resets", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  userId: uuid("user_id").notNull(),
  token: text("token").notNull().unique(),
  createdByUserId: uuid("created_by_user_id").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  usedAt: timestamp("used_at", { withTimezone: true }),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;
export type Team = typeof teams.$inferSelect;
export type NewTeam = typeof teams.$inferInsert;
export type TeamMember = typeof teamMembers.$inferSelect;
export type NewTeamMember = typeof teamMembers.$inferInsert;
export type Invite = typeof invites.$inferSelect;
export type NewInvite = typeof invites.$inferInsert;
export type PasswordReset = typeof passwordResets.$inferSelect;
export type NewPasswordReset = typeof passwordResets.$inferInsert;
export type BrandMember = typeof brandMembers.$inferSelect;
export type NewBrandMember = typeof brandMembers.$inferInsert;
/**
 * Team roles, in descending privilege order:
 *   admin   — full team + workspace management (invites, role changes, brand
 *             creation/deletion, Done-For-You client toggle).
 *   manager — a member who additionally can see and use the Client Command
 *             Center (client share links + feedback triage) for DFY clients.
 *             No team-management powers.
 *   member  — read/use access to the creative tools only; never sees the
 *             Client Console.
 * Stored as free text in team_members.role; no DB enum so adding a role is a
 * code-only change.
 */
export type Role = "admin" | "manager" | "member";

// ──────────────────────────────────────────────────────────────────────────
// LISTICLE BUILDER
//
// Two tables. A `listicle` row holds the draft + its publish state through
// every step of the builder: copy generation → image generation → HTML
// rendering → LanderLab deploy. The `listicle_images` rows are per-section
// (one image per numbered reason in the listicle) with the same approve /
// regen / feedback lifecycle the b-roll apps use.
//
// State machine on listicles.status:
//   drafting   — copy step in progress (or just saved)
//   images     — copy approved, image generation in progress / under review
//   rendering  — HTML render in progress
//   ready      — HTML rendered, user reviewing preview, hasn't deployed yet
//   deployed   — pushed to LanderLab; landerlab_lander_id, landerlab_variant_id
//                and the URL fields are populated
//   failed     — terminal error somewhere; see `error` field for details
// ──────────────────────────────────────────────────────────────────────────

export const listicles = pgTable("listicles", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  productId: uuid("product_id").notNull(),
  /** "generate" (Copy Engine), "paste" (user-supplied), "winning_ad" (analyzed from uploaded ad) */
  source: text("source").notNull(),
  status: text("status").notNull().default("drafting"), // drafting | analyzing | images | rendering | ready | deployed | failed
  angleName: text("angle_name"),
  language: text("language").notNull().default("en"),
  /** The user's destination URL — the offer/checkout page. Used for CTA_URL + offer extraction. */
  destinationUrl: text("destination_url"),
  /** Structured offer fields extracted from destinationUrl via the offer_extract prompt */
  offerExtract: jsonb("offer_extract"),
  /** The listicle markdown — either generated or pasted */
  copyMarkdown: text("copy_markdown"),
  /** Free-form guidance the user provided alongside the copy generation request */
  guidance: text("guidance"),
  /** Winning ad workflow: fal.storage URL of the uploaded ad (video .mp4/.mov or static .jpg/.png). Null for other sources. */
  winningAdUrl: text("winning_ad_url"),
  /** Winning ad workflow: "video" | "static" */
  winningAdType: text("winning_ad_type"),
  /** Winning ad workflow: full audio transcript from fal whisper. Null for static ads or other sources. */
  winningAdTranscript: text("winning_ad_transcript"),
  /** Winning ad workflow: structured angle JSON extracted by ad_extract_angle prompt. Shape: { primary_angle_name, hook, mechanism, target_pain, key_claims[], tone, creative_format, summary } */
  winningAdAnalysis: jsonb("winning_ad_analysis"),
  /** The fully-rendered HTML page (output of listicle_lander_html prompt). Stored verbatim. */
  renderedHtml: text("rendered_html"),
  /** User feedback when regenerating the HTML render */
  htmlFeedback: text("html_feedback"),
  /** LanderLab identifiers — populated when status >= 'deployed' */
  landerlabLanderId: text("landerlab_lander_id"),
  landerlabVariantId: text("landerlab_variant_id"),
  landerlabEncryptedVariantId: text("landerlab_encrypted_variant_id"),
  landerlabDomainId: text("landerlab_domain_id"),
  publishedUrl: text("published_url"),
  previewUrl: text("preview_url"),
  editorUrl: text("editor_url"),
  error: text("error"),
});

export const listicleImages = pgTable("listicle_images", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  listicleId: uuid("listicle_id").notNull(),
  /** Section number (1-based), matching the listicle's numbered sections */
  sectionIdx: integer("section_idx").notNull(),
  /** Headline of the section this image illustrates */
  sectionHeadline: text("section_headline"),
  /** The image-generation prompt produced by listicle_image_prompts */
  imagePrompt: text("image_prompt"),
  /** fal.ai output URL once generated */
  imageUrl: text("image_url"),
  imageStatus: text("image_status").notNull().default("idle"), // idle | generating | ready | failed
  imageApproval: text("image_approval").notNull().default("pending"), // pending | approved | rejected
  imageFeedback: text("image_feedback"),
  imageError: text("image_error"),
});

export type Listicle = typeof listicles.$inferSelect;
export type NewListicle = typeof listicles.$inferInsert;
export type ListicleImage = typeof listicleImages.$inferSelect;
export type NewListicleImage = typeof listicleImages.$inferInsert;

// ──────────────────────────────────────────────────────────────────────────
// AD CREATIVE CONSOLE
//
// A swipeable "command center" of proven ad ideas + trending organic content,
// filtered to a brand's niche and competitors and ranked by traction. The data
// model has two layers (see spec §5):
//
//   SHARED  — `niche_streams` is pulled once per niche and reused across every
//             brand in that niche (saves Apify credits). `ad_creatives` and
//             `organic_posts` are a GLOBAL deduped pool keyed by the source's
//             own ID — the same long-running competitor ad discovered for two
//             brands is stored once.
//   PER-BRAND — `competitors` (that brand's rivals), `brand_keyword_sets`
//             (keyword_extract output per angle), and `feed_items` (the ranked
//             queue linking a brand to pooled creatives/posts, with the
//             per-brand relevance + composite scores). `feed_events` logs every
//             swipe.
//
// Scoring split: `tractionScore` is INTRINSIC to a creative/post (longevity for
// ads, views+engagement for organic) so it lives on the pooled rows.
// `relevanceScore` and `compositeScore` depend on the viewing brand's keywords,
// so they live on `feed_items` (per brand) — a deliberate deviation from the
// spec §9 sketch, which put them on the creative for a single-brand v1.
// ──────────────────────────────────────────────────────────────────────────

/**
 * One shared stream per niche (e.g. "supplement", "skincare"). Pulled once and
 * reused by every brand of that niche. Holds the broad, brand-independent seed
 * config: category keyword/hashtag lists used for the weekly broad pull, the
 * niche's leading advertisers (for direct ad-library pulls), and adjacency
 * pain-point keywords. Refreshed weekly; `lastRefreshedAt` gates the next pull.
 */
export const nicheStreams = pgTable("niche_streams", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  niche: text("niche").notNull(), // "supplement" | "skincare" | ...  (matches brands.nicheType)
  displayName: text("display_name").notNull(),
  /** { adLibrary: string[], organic: string[], hashtags: string[] } — broad category queries for the weekly niche pull. */
  keywords: jsonb("keywords"),
  /** [{ name, fbPageUrl?, fbPageId?, igHandle?, tiktokHandle? }] — known leading advertisers for direct pulls. */
  leadingAdvertisers: jsonb("leading_advertisers"),
  /** string[] — adjacency problem/outcome keywords for organic discovery. */
  painPointKeywords: jsonb("pain_point_keywords"),
  /** Optional per-stream tuning: scoring weights + per-run credit caps. */
  config: jsonb("config"),
  lastRefreshedAt: timestamp("last_refreshed_at", { withTimezone: true }),
}, (t) => ({
  uniqNiche: uniqueIndex("niche_streams_niche_uniq").on(t.niche),
}));

/**
 * A single competitor of a brand. Auto-discovered (LLM web_search) or
 * manually added by the operator. We pull this advertiser's ads + organic
 * directly (the "brand overlay" half of the feed). `dedupeKey` is an
 * app-normalized identity (page id or lowercased handle) so a competitor can't
 * be added twice for the same brand whether by auto-discovery or by hand.
 */
export const competitors = pgTable("competitors", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  name: text("name").notNull(),
  fbPageUrl: text("fb_page_url"),
  fbPageId: text("fb_page_id"),
  igHandle: text("ig_handle"),
  tiktokHandle: text("tiktok_handle"),
  adspyAdvertiserId: text("adspy_advertiser_id"),   // resolved + cached AdSpy advertiser userId (verified)
  adspyVerified: boolean("adspy_verified").notNull().default(false),
  source: text("source").notNull(), // "auto" | "manual"
  status: text("status").notNull().default("active"), // active | archived
  /** Why auto-discovery surfaced this competitor (LLM rationale); null for manual adds. */
  discoveryReason: text("discovery_reason"),
  /** App-computed identity for dedup: fbPageId ?? lowercased igHandle ?? lowercased name. */
  dedupeKey: text("dedupe_key").notNull(),
  createdBy: uuid("created_by"), // operator who manually added it; null = auto-discovered
}, (t) => ({
  uniqBrandDedupe: uniqueIndex("competitors_brand_dedupe_uniq").on(t.brandId, t.dedupeKey),
}));

/**
 * keyword_extract output for one (brand, angle). Three sections × 20 keywords
 * (Problem / Desired-outcome / Product-solution). Section 3 → ad-library
 * queries; Sections 1+2 → organic queries (spec §6.1). Generated async (status
 * lifecycle mirrors the other LLM-action tables). Unique per (brand, angle) so
 * a regeneration upserts rather than piling up.
 */
export const brandKeywordSets = pgTable("brand_keyword_sets", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  productId: uuid("product_id"), // soft ref — the product whose research seeded the extract
  angleId: text("angle_id").notNull(),
  angleName: text("angle_name"),
  problemKeywords: jsonb("problem_keywords"), // string[] — Section 1 (20)
  outcomeKeywords: jsonb("outcome_keywords"), // string[] — Section 2 (20)
  productKeywords: jsonb("product_keywords"), // string[] — Section 3 (20)
  status: text("status").notNull().default("pending"), // pending | running | complete | failed
  error: text("error"),
  model: text("model"),
  promptVersion: text("prompt_version"),
}, (t) => ({
  uniqBrandAngle: uniqueIndex("brand_keyword_sets_brand_angle_uniq").on(t.brandId, t.angleId),
}));

/**
 * GLOBAL deduped pool of scraped ad-library creatives (curious_coder FB ads
 * scraper). Keyed by the ad's own archive id so the same ad discovered for
 * multiple brands is stored once. Traction = longevity proxy (spec §7): there
 * is no US/CA impression data, so a long `runtimeDays` is the "this ad wins"
 * signal. `nicheStreamId` / `competitorId` record HOW it was first discovered
 * (broad niche pull vs a specific competitor), not exclusive ownership.
 */
export const adCreatives = pgTable("ad_creatives", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  source: text("source").notNull().default("facebook_ads"), // "adspy" (current) | "facebook_ads" (legacy Meta) — always set explicitly by writers
  externalId: text("external_id").notNull(), // AdSpy ad id (legacy: Meta ad_archive_id) — dedup key
  advertiserName: text("advertiser_name"),
  pageId: text("page_id"),
  pageUrl: text("page_url"),
  mediaUrls: jsonb("media_urls"), // string[] — creative image/video URLs
  thumbnailUrl: text("thumbnail_url"),
  format: text("format"), // "static" | "video"
  copy: text("copy"), // primary ad text
  cta: text("cta"),
  landingUrl: text("landing_url"),
  adStart: timestamp("ad_start", { withTimezone: true }),
  adStop: timestamp("ad_stop", { withTimezone: true }),
  runtimeDays: integer("runtime_days"), // AdSpy days_active (legacy: (adStop ?? today) − adStart)
  isActive: boolean("is_active"),
  variationCount: integer("variation_count"),
  // AdSpy engagement — `shares` (snapshot.shareNum) is the rank driver; `likes`
  // for display; `deepLinkUrl` (linkToAd) opens the live FB/IG post.
  shares: integer("shares"),
  likes: integer("likes"),
  deepLinkUrl: text("deep_link_url"),
  tractionScore: numeric("traction_score", { precision: 10, scale: 4 }), // 0..1 (AdSpy: log-scaled shares)
  // Tier-2 enrichment (deferred) — populated later for top-N items only.
  hook: text("hook"),
  transcript: text("transcript"),
  // Discovery provenance (first writer wins).
  nicheStreamId: uuid("niche_stream_id"),
  competitorId: uuid("competitor_id"),
  discoveryQuery: text("discovery_query"), // angle query that surfaced this niche ad — drives relevance (provenance, not copy)
  rawJson: jsonb("raw_json"), // full AdSpy ad item for re-derivation / debugging
}, (t) => ({
  uniqSourceExternal: uniqueIndex("ad_creatives_source_external_uniq").on(t.source, t.externalId),
}));

/**
 * GLOBAL deduped pool of scraped organic posts (IG reels + TikTok). Keyed by
 * (source, post id). IG transcripts come FREE from the scraper, so IG cards can
 * show a script/hook with no extra LLM cost (spec §4). Traction = views floor +
 * engagement + recency (no outlier scoring in v1).
 */
export const organicPosts = pgTable("organic_posts", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  source: text("source").notNull(), // "instagram" | "tiktok"
  externalId: text("external_id").notNull(), // post / reel id — dedup key
  handle: text("handle"),
  profileName: text("profile_name"),
  postUrl: text("post_url"),
  mediaUrl: text("media_url"),
  thumbnailUrl: text("thumbnail_url"),
  caption: text("caption"),
  hashtags: jsonb("hashtags"), // string[]
  views: integer("views"),
  likes: integer("likes"),
  comments: integer("comments"),
  shares: integer("shares"), // IG reshares / TikTok shareCount — the IG virality metric
  bookmarks: integer("bookmarks"), // TikTok saves (collectCount) — the TikTok virality metric (IG has no save count)
  durationSec: integer("duration_sec"), // clip length in seconds
  postedAt: timestamp("posted_at", { withTimezone: true }),
  transcript: text("transcript"), // FREE for IG; deferred (paid) for TikTok
  format: text("format").notNull().default("video"), // reels/tiktok are video
  tractionScore: numeric("traction_score", { precision: 10, scale: 4 }),
  hook: text("hook"), // tier-2 (deferred)
  nicheStreamId: uuid("niche_stream_id"),
  rawJson: jsonb("raw_json"),
}, (t) => ({
  uniqSourceExternal: uniqueIndex("organic_posts_source_external_uniq").on(t.source, t.externalId),
}));

/**
 * The per-brand ranked queue. One row links a brand to a pooled ad_creative OR
 * organic_post, carrying the BRAND-SPECIFIC relevance + composite scores and
 * the swipe status. `rail` places it in the UI (competitor/niche ads vs
 * trending organic vs the weekly-ideas rail). `refKey` = `${itemType}:${refId}`
 * gives a single dedup key so the same creative is queued at most once per
 * brand.
 */
export const feedItems = pgTable("feed_items", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  itemType: text("item_type").notNull(), // "ad" | "organic"
  adCreativeId: uuid("ad_creative_id"), // set when itemType = "ad"
  organicPostId: uuid("organic_post_id"), // set when itemType = "organic"
  rail: text("rail").notNull(), // "competitor_ads" | "trending_organic" | "weekly_ideas"
  refKey: text("ref_key").notNull(), // `${itemType}:${refId}` — per-brand dedup
  relevanceScore: numeric("relevance_score", { precision: 10, scale: 4 }),
  compositeScore: numeric("composite_score", { precision: 10, scale: 4 }),
  matchedKeywords: jsonb("matched_keywords"), // string[] — why it was deemed relevant
  status: text("status").notNull().default("new"), // new | selected | skipped
  tier2Enriched: boolean("tier2_enriched").notNull().default(false),
}, (t) => ({
  uniqBrandRef: uniqueIndex("feed_items_brand_ref_uniq").on(t.brandId, t.refKey),
}));

/**
 * Append-only swipe log. Every select / skip / revise / view on a feed item is
 * recorded here — powers the swipe UX (don't re-show actioned items) and a
 * future relevance-learning loop.
 */
export const feedEvents = pgTable("feed_events", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  feedItemId: uuid("feed_item_id").notNull(),
  userId: uuid("user_id"), // operator who swiped
  event: text("event").notNull(), // "select" | "skip" | "revise" | "view"
  metadata: jsonb("metadata"), // e.g. emitted Creative Brief, routed app
});

/**
 * Ad Pipeline — durable Kanban card. Snapshots the CreativeBrief on "Make it
 * mine" so the card survives feed re-ranking (feed_items are ephemeral). Outputs
 * are NOT stored here: they live in `generations` (live draft, tagged with
 * pipelineCardId in inputs) and `brand_assets` (curated keeper, tagged in
 * metadata). A card reaches `ready` only once a brand asset is saved for it.
 */
export const adPipelineCards = pgTable("ad_pipeline_cards", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  stage: text("stage").notNull().default("idea"), // "idea" | "in_production" | "ready"
  sourceType: text("source_type").notNull(), // "ad" | "organic"
  format: text("format").notNull(), // "video" | "static"
  brief: jsonb("brief").notNull(), // full CreativeBrief snapshot
  sourceUrl: text("source_url"), // original reference (the card's link)
  originalScript: text("original_script"), // transcript (from brief, or filled by enrichment)
  referenceImageUrl: text("reference_image_url"), // static: creative image to recreate from
  staticReferenceId: uuid("static_reference_id"), // static: the created static_ad_reference
  productId: uuid("product_id"), // chosen at recreate time (null while in Idea)
  angleName: text("angle_name"), // chosen at recreate time
  language: text("language").notNull().default("en"),
  bgJobStatus: text("bg_job_status").notNull().default("pending"), // pending|running|complete|failed
  bgJobError: text("bg_job_error"),
}, (t) => ({
  brandIdx: index("ad_pipeline_cards_brand_idx").on(t.brandId),
}));

/**
 * LLM-GENERATED weekly creative ideas — the "This Week's Ideas" rail (spec §5,
 * `weekly_ideas`). UNLIKE the competitor/organic rails (which queue real scraped
 * creatives via feed_items), these are fresh ad concepts the model invents FOR
 * this brand, grounded in its niche + extracted keywords + the top-ranked feed
 * cards it just pulled. One generation run shares a `batchId`; the Console shows
 * the newest batch. `status` mirrors the feed swipe lifecycle (new/selected/
 * skipped) so the rail behaves like the others.
 */
export const adConsoleIdeas = pgTable("ad_console_ideas", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  brandId: uuid("brand_id").notNull(),
  batchId: uuid("batch_id").notNull(), // groups one generation run
  title: text("title"), // short label for the idea card
  hook: text("hook"), // the scroll-stopping opening line
  concept: text("concept"), // what the ad does — the creative concept
  format: text("format"), // "static" | "video" | "ugc"
  angle: text("angle"), // which strategic angle it leans on
  rationale: text("rationale"), // why it should work (grounded in observed traction)
  sourceRefs: jsonb("source_refs"), // [{ type: "ad" | "organic", refId, note }] — grounding
  status: text("status").notNull().default("new"), // new | selected | skipped
  model: text("model"),
  promptVersion: text("prompt_version"),
});

export type NicheStream = typeof nicheStreams.$inferSelect;
export type NewNicheStream = typeof nicheStreams.$inferInsert;
export type Competitor = typeof competitors.$inferSelect;
export type NewCompetitor = typeof competitors.$inferInsert;
export type BrandKeywordSet = typeof brandKeywordSets.$inferSelect;
export type NewBrandKeywordSet = typeof brandKeywordSets.$inferInsert;
export type AdCreative = typeof adCreatives.$inferSelect;
export type NewAdCreative = typeof adCreatives.$inferInsert;
export type OrganicPost = typeof organicPosts.$inferSelect;
export type NewOrganicPost = typeof organicPosts.$inferInsert;
export type FeedItem = typeof feedItems.$inferSelect;
export type NewFeedItem = typeof feedItems.$inferInsert;
export type FeedEvent = typeof feedEvents.$inferSelect;
export type NewFeedEvent = typeof feedEvents.$inferInsert;
export type AdConsoleIdea = typeof adConsoleIdeas.$inferSelect;
export type NewAdConsoleIdea = typeof adConsoleIdeas.$inferInsert;
export type AdPipelineCard = typeof adPipelineCards.$inferSelect;
export type NewAdPipelineCard = typeof adPipelineCards.$inferInsert;

/**
 * Durable generation jobs. One row per user-triggered batch ("Generate all
 * images" = one job). The runner (server/lib/jobRunner.ts) processes items
 * server-side so batches survive tab closes and deploys; payload snapshots
 * the app session at trigger time so the app can restore full working state.
 * Spec: docs/superpowers/specs/2026-07-08-generation-jobs-design.md
 */
export const jobs = pgTable("jobs", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  brandId: uuid("brand_id").notNull(),
  userId: uuid("user_id"), // creator, from req.auth
  productId: uuid("product_id"), // soft ref
  app: text("app").notNull(), // "broll" | "character_broll" | "single_scene" | "message_testing" | "listicle" | "copy_engine"
  type: text("type").notNull(), // runner registry key: "broll_images" | "broll_videos" | ...
  status: text("status").notNull().default("queued"), // queued | running | complete | complete_with_errors | failed
  title: text("title").notNull(),
  payload: jsonb("payload").notNull(), // full session snapshot at trigger time
  totalCount: integer("total_count").notNull().default(0),
  doneCount: integer("done_count").notNull().default(0),
  errorCount: integer("error_count").notNull().default(0),
  error: text("error"), // job-fatal error only
}, (t) => ({
  brandStatusIdx: index("jobs_brand_status_idx").on(t.brandId, t.status, t.createdAt),
}));

export const jobItems = pgTable("job_items", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  jobId: uuid("job_id").notNull(),
  idx: integer("idx").notNull(), // stable ordering
  label: text("label").notNull(), // shot title
  status: text("status").notNull().default("pending"), // pending | running | complete | failed
  attempts: integer("attempts").notNull().default(0),
  input: jsonb("input").notNull(), // { shotId, kind: "image"|"video", model, falInput }
  output: jsonb("output"), // { url, model, durationMs }
  error: text("error"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
}, (t) => ({
  jobIdIdx: index("job_items_job_idx").on(t.jobId),
}));

export type Job = typeof jobs.$inferSelect;
export type JobItem = typeof jobItems.$inferSelect;
export type NewJob = typeof jobs.$inferInsert;
export type NewJobItem = typeof jobItems.$inferInsert;
